In [86]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [93]:
os.getcwd()

'/mnt/d/0ngoing/thesis/repo/paper/my_writing/imgs'

In [88]:
y_test = pd.read_csv("../../../assets/y_hats/multivariate/y_test.csv", index_col=[0, 1, 2])

ind_cat.csv にない13企業

* 上場廃止, 合併 --> 日経コードでFQ検索 https://www.jpx.co.jp/listing/stocks/delisted/index.html

* 改名 --> 改名した後の名前を持ってくる https://www.jpx.co.jp/listing/others/changed/index.html

'エフ・ジェー・ネクスト': 8935, --> "ＦＪネクストホールディングス"

'ココカラファイン': 3098, --> 2021/09/29

'タケエイ': 2151, --> 2021/09/29

'ビオフェルミン製薬': 4517, --> 2021/07/28

'フルサト工業': 8087, --> 2021/09/29

'マツモトキヨシホールディングス': 3088, --> "マツキヨココカラ＆カンパニー"

'ヤマエ久野': 8108, --> 2021/09/29

'京都きもの友禅': 7615, --> "ＹＵ－ＷＡ　Ｃｒｅａｔｉｏｎ　Ｈｏｌｄｉｎｇｓ"

'前田建設工業': 1824, --> 2021/09/29

'前田道路': 1883, --> 2021/09/29

'協和エクシオ': 1951, --> "エクシオグループ"

'船井電機': 6839, --> 2021/08/26

'蛇の目ミシン工業': 6445 --> 'ジャノメ'

# 業種コードtable

In [99]:
ind_cat = pd.read_excel("../../../data/raw/FQ/CORPORATE/ind_cat_with_ommit_and_renamed_.xlsx")
ind_cat = ind_cat.drop([0, 1])
ind_cat = ind_cat.drop(["Unnamed: 2", "Unnamed: 3"], axis=1)
ind_cat = ind_cat.rename(columns={'Unnamed: 0': '企業名', 'Unnamed: 1': 'NKCODE'})
ind_cat = ind_cat.set_index("企業名")
# change old name
ind_cat = ind_cat.rename(index={
    "ＦＪネクストホールディングス": 'エフ・ジェー・ネクスト',
    "ココカラファイングループ": 'ココカラファイン',
    "マツキヨココカラ＆カンパニー": 'マツモトキヨシホールディングス',
    "ＹＵ－ＷＡ　Ｃｒｅａｔｉｏｎ": '京都きもの友禅',
    "エクシオグループ": '協和エクシオ',
    "ジャノメ": '蛇の目ミシン工業'
    })
ind_cat = ind_cat.loc[y_test.index.get_level_values(0).unique()].drop_duplicates()    
ind_cat.to_csv("ind_cat.csv")

In [132]:
# ind_cat["東証業種名（漢字）"].value_counts().to_csv("ind_cat_table.csv")
cat_name = ind_cat["東証業種名（漢字）"].value_counts().reset_index()
cat_name.columns = ["業種名", "企業数"]
cat_code = ind_cat["東証業種コード"].value_counts().reset_index()
cat_code.columns = ["業種コード", "企業数"]
cat_code = cat_code["業種コード"]
pd.concat([cat_code, cat_name], axis=1).to_csv("ind_cat_table.csv")
pd.concat([cat_code, cat_name], axis=1)

   業種コード       業種名  企業数
0   3650      電気機器  116
1   6050       卸売業  105
2   3200        化学   97
3   3600        機械   96
4   5250    情報・通信業   75
5   2050       建設業   74
6   9050     サービス業   61
7   6100       小売業   60
8   3700     輸送用機器   49
9   3050       食料品   46
10  5050       陸運業   35
11  3800     その他製品   31
12  3450        鉄鋼   29
13  3400  ガラス・土石製品   25
14  3550      金属製品   25
15  3100      繊維製品   24
16  3250       医薬品   24
17  8050      不動産業   22
18  3750      精密機器   21
19  3500      非鉄金属   18
20  5200  倉庫・運輸関連業   13
21  3150     パルプ・紙    9
22  3350      ゴム製品    7
23  5100       海運業    7
24  4050    電気・ガス業    7
25  3300   石油・石炭製品    5
26  0050    水産・農林業    3
27  1050        鉱業    3
28  5150       空運業    2

# 変数の記述統計

In [104]:
tidy_df = pd.read_csv("../../../data/processed/tidy_df.csv", index_col=[0, 1, 2])
tidy_df

                     決算発表日 事業年度開始年月日［３ヵ月］   事業年度終了年月日        EPS         INV  \
企業名   会計年度 四半期
あらた   2008 Q1   2008-08-12     2008-04-01  2008-06-30   2.660000  400.874539
           Q2   2008-11-12     2008-07-01  2008-09-30   2.420000  354.438952
           Q3   2009-02-12     2008-10-01  2008-12-31   3.140000  463.063689
           Q4   2009-05-15     2009-01-01  2009-03-31  -5.480000  352.113272
      2009 Q1   2009-08-10     2009-04-01  2009-06-30   6.780000  342.920625
...                    ...            ...         ...        ...         ...
ｅＢＡＳＥ 2019 Q4   2020-05-15     2020-01-01  2020-03-31  18.657982    0.042405
      2020 Q1   2020-07-31     2020-04-01  2020-06-30   2.010000    0.084809
           Q2   2020-10-30     2020-07-01  2020-09-30   3.810000    0.086835
           Q3   2021-01-29     2020-10-01  2020-12-31   3.070000    0.108546
           Q4   2021-05-14            NaN  2021-03-31   9.989365    0.108580

                         AR       CAPX          GM          SA       ETR  \
企業名   会計年度 四半期
あらた   2008 Q1   1097.393673   9.570469  277.799816  282.517228  0.667780
           Q2    947.010117  13.330285  245.357228  247.716689  0.645914
           Q3   1227.472337  24.209869  257.865737  255.535304  0.734463
           Q4    937.498755  27.924985  224.785468  237.362369 -0.300633
      2009 Q1    992.622168   5.478945  258.643522  255.350823  0.546833
...                     ...        ...         ...         ...       ...
ｅＢＡＳＥ 2019 Q4     40.920347   0.657270   38.291268   11.194789  0.282680
      2020 Q1     12.615340   0.148416    8.268878    5.533788  0.321168
           Q2     11.527380   0.151962   11.201748    5.861380  0.308300
           Q3     11.744667   0.314783   10.181606    5.839770  0.315534
           Q4     18.328314   0.314882   19.848434    6.015335  0.281931

                       LF
企業名   会計年度 四半期
あらた   2008 Q1   17.678254
           Q2   17.681603
           Q3   17.765127
           Q4   17.575437
      2009 Q1   17.707993
...                   ...
ｅＢＡＳＥ 2019 Q4   15.012871
      2020 Q1   14.510928
           Q2   14.653348
           Q3   14.605000
           Q4   14.970051

[56628 rows x 11 columns]

In [105]:
tidy_df.describe().to_csv("variable_sum_table.csv")
tidy_df.describe()

,EPS,INV,AR,CAPX,GM,SA,ETR,LF
count,56628.000000,56628.000000,56628.000000,56628.000000,56628.000000,56628.000000,56628.000000,56628.000000
mean,67.219409,781.733070,1273.860397,173.230231,508.658812,381.614042,0.346242,16.185539
std,690.524130,6963.552335,7971.923999,2312.546289,3497.303476,2636.875351,6.876806,0.789316
min,-37300.500000,-1248.280315,-8093.573906,-3424.537248,-30368.482179,-1970.903771,-494.716049,11.628080
25%,3.260000,90.115089,177.839614,9.381707,52.725080,39.485835,0.235611,15.645807
50%,14.880000,193.617631,355.497396,25.090398,115.000411,83.115920,0.330000,16.135532
75%,37.120000,410.684878,713.659557,65.736542,220.324184,164.602388,0.414576,16.670491
max,31202.830000,404482.462266,293004.896357,143224.389801,104813.929669,87333.560942,882.000000,22.530918

In [106]:
# EPSのmin, ETRのminがやばくね? 極地上下0.5%を含む企業は落とすべき?
tidy_df[tidy_df["EPS"] == tidy_df["EPS"].min()]

,,,決算発表日,事業年度開始年月日［３ヵ月］,事業年度終了年月日,EPS,INV,AR,CAPX,GM,SA,ETR,LF
企業名,会計年度,四半期,,,,,,,,,,,
サンフロンティア不動産,2008,Q3,2009-01-29,2008-10-01,2008-12-31,-37300.5,89880.692016,271.497308,36.199641,-30368.482179,2452.525679,-0.119117,17.330149

In [107]:
tidy_df[tidy_df["ETR"] == tidy_df["ETR"].min()]

,,,決算発表日,事業年度開始年月日［３ヵ月］,事業年度終了年月日,EPS,INV,AR,CAPX,GM,SA,ETR,LF
企業名,会計年度,四半期,,,,,,,,,,,
ソニーグループ,2011,Q4,2012-05-10,2012-01-01,2012-03-31,-254.3,704.531013,837.925694,381.185025,490.327487,353.409413,-494.716049,16.101628

# 変数の相関行列

In [108]:
tidy_df.corr()

,EPS,INV,AR,CAPX,GM,SA,ETR,LF
EPS,1.000000,0.289594,0.434839,0.379530,0.710259,0.495982,0.000887,0.037598
INV,0.289594,1.000000,0.523715,0.159936,0.520813,0.528124,0.001286,0.066478
AR,0.434839,0.523715,1.000000,0.301611,0.705616,0.717532,0.001945,0.073436
CAPX,0.379530,0.159936,0.301611,1.000000,0.549838,0.461640,0.000443,0.005316
GM,0.710259,0.520813,0.705616,0.549838,1.000000,0.950087,0.002498,0.044226
SA,0.495982,0.528124,0.717532,0.461640,0.950087,1.000000,0.002791,0.041377
ETR,0.000887,0.001286,0.001945,0.000443,0.002498,0.002791,1.000000,0.004728
LF,0.037598,0.066478,0.073436,0.005316,0.044226,0.041377,0.004728,1.000000

In [111]:
tidy_df_lag = pd.read_csv("../../../data/processed/tidy_df_lag.csv", index_col=[0, 1, 2])
tidy_df_lag.describe()

,EPS,INV,AR,CAPX,GM,SA,ETR,LF,EPS_-1,INV_-1,...,ETR_-8,LF_-8,EPS_-9,INV_-9,AR_-9,CAPX_-9,GM_-9,SA_-9,ETR_-9,LF_-9
count,56628.000000,56628.000000,56628.000000,56628.000000,56628.000000,56628.000000,56628.000000,56628.000000,55539.000000,55539.000000,...,47916.000000,47916.000000,46827.000000,46827.000000,46827.000000,46827.000000,46827.000000,46827.000000,46827.000000,46827.000000
mean,67.219409,781.733070,1273.860397,173.230231,508.658812,381.614042,0.346242,16.185539,67.754568,786.215836,...,0.360894,16.189268,74.688641,824.564602,1340.000635,191.843498,567.454377,424.964384,0.367485,16.187039
std,690.524130,6963.552335,7971.923999,2312.546289,3497.303476,2636.875351,6.876806,0.789316,697.068572,7030.751846,...,7.218257,0.792135,758.154942,7649.989118,8742.815445,2542.051638,3842.140657,2896.885427,7.286946,0.792745
min,-37300.500000,-1248.280315,-8093.573906,-3424.537248,-30368.482179,-1970.903771,-494.716049,11.628080,-37300.500000,-1248.280315,...,-494.716049,11.628080,-37300.500000,-1248.280315,-8093.573906,-3424.537248,-30368.482179,-1970.903771,-494.716049,11.628080
25%,3.260000,90.115089,177.839614,9.381707,52.725080,39.485835,0.235611,15.645807,3.240000,89.675058,...,0.240000,15.649329,3.050000,84.840795,167.498452,8.540278,47.515832,36.031253,0.241732,15.647366
50%,14.880000,193.617631,355.497396,25.090398,115.000411,83.115920,0.330000,16.135532,14.690000,192.129383,...,0.339248,16.140402,13.280000,177.121045,326.302328,22.460404,103.597901,74.531617,0.340868,16.138009
75%,37.120000,410.684878,713.659557,65.736542,220.324184,164.602388,0.414576,16.670491,36.580000,405.955193,...,0.422809,16.673242,33.510000,355.998804,639.368182,58.101966,203.509256,151.471450,0.423805,16.670883
max,31202.830000,404482.462266,293004.896357,143224.389801,104813.929669,87333.560942,882.000000,22.530918,31202.830000,404482.462266,...,882.000000,22.530918,31202.830000,404482.462266,293004.896357,143224.389801,104813.929669,87333.560942,882.000000,22.530918

In [118]:
tidy_df_lag = tidy_df_lag[[
    "EPS", 
    "EPS_-1", "EPS_-2", "EPS_-3", "EPS_-4", 
    "INV_-1", "INV_-2", "INV_-3", "INV_-4", 
    "AR_-1", "AR_-2", "AR_-3", "AR_-4", 
    "CAPX_-1", "CAPX_-2", "CAPX_-3", "CAPX_-4", 
    "GM_-1", "GM_-2", "GM_-3", "GM_-4", 
    "SA_-1", "SA_-2", "SA_-3", "SA_-4", 
    "ETR_-1", "ETR_-2", "ETR_-3", "ETR_-4", 
    "LF_-1", "LF_-2", "LF_-3", "LF_-4", 
    ]]

In [119]:
tidy_df_lag.describe()

,EPS,EPS_-1,EPS_-2,EPS_-3,EPS_-4,INV_-1,INV_-2,INV_-3,INV_-4,AR_-1,...,SA_-3,SA_-4,ETR_-1,ETR_-2,ETR_-3,ETR_-4,LF_-1,LF_-2,LF_-3,LF_-4
count,56628.000000,55539.000000,54450.000000,53361.000000,52272.000000,55539.000000,54450.000000,53361.000000,52272.000000,55539.000000,...,53361.000000,52272.000000,55539.000000,54450.000000,53361.000000,52272.000000,55539.000000,54450.000000,53361.000000,52272.000000
mean,67.219409,67.754568,68.187386,69.059970,70.299180,786.215836,790.398383,794.778237,798.865968,1279.532592,...,394.532743,399.386241,0.348084,0.350707,0.352233,0.352288,16.184686,16.184687,16.186622,16.191248
std,690.524130,697.068572,703.901825,710.939179,718.179733,7030.751846,7099.952509,7171.250528,7244.715868,8047.318079,...,2715.576074,2743.420985,6.939093,7.004247,7.071644,7.126016,0.790132,0.790226,0.790505,0.789556
min,-37300.500000,-37300.500000,-37300.500000,-37300.500000,-37300.500000,-1248.280315,-1248.280315,-1248.280315,-1248.280315,-8093.573906,...,-1970.903771,-1970.903771,-494.716049,-494.716049,-494.716049,-494.716049,11.628080,11.628080,11.628080,11.628080
25%,3.260000,3.240000,3.170000,3.170000,3.260000,89.675058,89.124611,88.479118,87.848778,176.758821,...,38.521957,38.208630,0.237717,0.237861,0.238866,0.240090,15.644276,15.644710,15.647100,15.652560
50%,14.880000,14.690000,14.410000,14.280000,14.330000,192.129383,190.311218,188.365888,186.227103,352.127564,...,80.784314,79.986635,0.331166,0.332277,0.333333,0.334228,16.134415,16.134853,16.137240,16.141436
75%,37.120000,36.580000,35.990000,35.790000,35.830000,405.955193,400.848308,394.015838,388.027894,705.415801,...,161.115990,160.104090,0.415414,0.416724,0.418001,0.418865,16.670126,16.669554,16.671500,16.674549
max,31202.830000,31202.830000,31202.830000,31202.830000,31202.830000,404482.462266,404482.462266,404482.462266,404482.462266,293004.896357,...,87333.560942,87333.560942,882.000000,882.000000,882.000000,882.000000,22.530918,22.530918,22.530918,22.530918

In [121]:
tidy_df_lag.corr().to_csv("variable_lag_corr_table.csv")
tidy_df_lag.corr()

,EPS,EPS_-1,EPS_-2,EPS_-3,EPS_-4,INV_-1,INV_-2,INV_-3,INV_-4,AR_-1,...,SA_-3,SA_-4,ETR_-1,ETR_-2,ETR_-3,ETR_-4,LF_-1,LF_-2,LF_-3,LF_-4
EPS,1.000000,0.521700,0.488933,0.478860,0.594732,0.269362,0.255099,0.277013,0.272546,0.405952,...,0.463058,0.447165,0.001459,0.002045,0.002309,0.000530,0.024423,0.024439,0.023564,0.032142
EPS_-1,0.521700,1.000000,0.521735,0.488985,0.478900,0.289622,0.269383,0.255124,0.277063,0.434907,...,0.461800,0.463182,0.000862,0.001443,0.002033,0.002305,0.037536,0.024325,0.024183,0.023112
EPS_-2,0.488933,0.521735,1.000000,0.521713,0.488982,0.303586,0.289615,0.269368,0.255110,0.395075,...,0.484788,0.461838,0.002673,0.000835,0.001408,0.002039,0.023183,0.037443,0.024043,0.023826
EPS_-3,0.478860,0.488985,0.521713,1.000000,0.521634,0.293286,0.303605,0.289629,0.269384,0.371209,...,0.496095,0.484786,0.001669,0.002641,0.000798,0.001420,0.025766,0.022907,0.037042,0.023293
EPS_-4,0.594732,0.478900,0.488982,0.521634,1.000000,0.276109,0.293303,0.303620,0.289643,0.336764,...,0.484632,0.496068,0.000990,0.001632,0.002615,0.000784,0.022986,0.025485,0.022293,0.036163
INV_-1,0.269362,0.289622,0.303586,0.293286,0.276109,1.000000,0.934776,0.891219,0.848870,0.523732,...,0.489287,0.469745,0.001281,0.001208,0.001095,0.001113,0.066700,0.066385,0.065685,0.065682
INV_-2,0.255099,0.269383,0.289615,0.303605,0.293303,0.934776,1.000000,0.934765,0.891197,0.502717,...,0.504186,0.489294,0.001195,0.001280,0.001193,0.001091,0.067889,0.066956,0.066556,0.065849
INV_-3,0.277013,0.255124,0.269368,0.289629,0.303620,0.891219,0.934765,1.000000,0.934751,0.481220,...,0.528134,0.504191,0.001088,0.001193,0.001265,0.001192,0.067709,0.068174,0.067158,0.066753
INV_-4,0.272546,0.277063,0.255110,0.269384,0.289643,0.848870,0.891197,0.934751,1.000000,0.464850,...,0.509563,0.528148,-0.000019,0.001088,0.001179,0.001271,0.067195,0.067980,0.068372,0.067351
AR_-1,0.405952,0.434907,0.395075,0.371209,0.336764,0.523732,0.502717,0.481220,0.464850,1.000000,...,0.652890,0.622116,0.001930,0.001963,0.001755,0.001842,0.073076,0.069617,0.068915,0.068004
AR_-2,0.400409,0.406024,0.434948,0.395118,0.371263,0.502955,0.523738,0.502716,0.481207,0.943123,...,0.683406,0.653021,0.002108,0.001904,0.001953,0.001783,0.068759,0.072735,0.069083,0.068280
AR_-3,0.399374,0.400473,0.406044,0.434977,0.395143,0.490247,0.502944,0.523737,0.502704,0.900559,...,0.717902,0.683494,0.001799,0.002080,0.001891,0.001976,0.067671,0.068532,0.072349,0.068539
AR_-4,0.387622,0.399454,0.400503,0.406068,0.435013,0.470120,0.490232,0.502936,0.523731,0.854603,...,0.684769,0.717997,0.001658,0.001773,0.002067,0.001908,0.066968,0.067447,0.068109,0.071819
CAPX_-1,0.396822,0.379616,0.477024,0.435626,0.349729,0.159907,0.158455,0.144132,0.134284,0.301655,...,0.413783,0.386487,0.000441,0.000577,0.000591,0.000742,0.005417,0.004826,0.004200,0.003731
CAPX_-2,0.431059,0.396926,0.379637,0.477069,0.435672,0.156230,0.159880,0.158428,0.144106,0.287904,...,0.443457,0.413768,0.000688,0.000429,0.000567,0.000583,0.003457,0.005466,0.004789,0.004065
CAPX_-3,0.452982,0.431178,0.396956,0.379642,0.477086,0.153781,0.156206,0.159854,0.158405,0.275879,...,0.461591,0.443418,0.000711,0.000669,0.000417,0.000563,0.002986,0.003494,0.005401,0.004555
CAPX_-4,0.356431,0.453132,0.431227,0.396967,0.379630,0.153125,0.153761,0.156182,0.159832,0.270342,...,0.450098,0.461549,0.000522,0.000690,0.000657,0.000411,0.003185,0.003016,0.003386,0.005131
GM_-1,0.573165,0.710375,0.579933,0.542478,0.495643,0.520806,0.501667,0.481994,0.470252,0.705727,...,0.875543,0.844590,0.002475,0.002612,0.002508,0.002689,0.044481,0.039048,0.039476,0.037679
GM_-2,0.551684,0.573269,0.710412,0.579925,0.542450,0.504808,0.520806,0.501662,0.481990,0.664619,...,0.909681,0.875528,0.002686,0.002438,0.002585,0.002517,0.038940,0.044637,0.038959,0.039192
GM_-3,0.549428,0.551797,0.573300,0.710428,0.579893,0.489673,0.504816,0.520815,0.501673,0.632064,...,0.950075,0.909668,0.002313,0.002646,0.002408,0.002592,0.039508,0.039062,0.044562,0.038590
GM_-4,0.573617,0.549566,0.551841,0.573289,0.710416,0.471880,0.489689,0.504831,0.520838,0.597629,...,0.907976,0.950071,-0.001017,0.002272,0.002616,0.002412,0.038931,0.039650,0.038921,0.044165
SA_-1,0.484652,0.496070,0.484660,0.449716,0.414745,0.528124,0.509556,0.489444,0.472065,0.717667,...,0.916280,0.879606,0.002768,0.002641,0.002412,0.002588,0.041665,0.041099,0.040978,0.039790
SA_-2,0.461693,0.484753,0.496096,0.484656,0.449687,0.504182,0.528128,0.509556,0.489445,0.683272,...,0.953678,0.916265,0.002546,0.002732,0.002612,0.002420,0.040805,0.041871,0.041095,0.040771
SA_-3,0.463058,0.461800,0.484788,0.496095,0.484632,0.489287,0.504186,0.528134,0.509563,0.652890,...,1.000000,0.953669,0.002248,0.002508,0.002703,0.002620,0.040857,0.041020,0.041873,0.040873
SA_-4,0.447165,0.463182,0.461838,0.484786,0.496068,0.469745,0.489294,0.504191,0.528148,0.622116,...,0.953669,1.000000,-0.001748,0.002210,0.002479,0.002711,0.040671,0.041093,0.041020,0.041638
ETR_-1,0.001459,0.000862,0.002673,0.001669,0.000990,0.001281,0.001195,0.001088,-0.000019,0.001930,...,0.002248,-0.001748,1.000000,-0.000116,-0.042191,0.002479,0.005099,0.003747,0.004060,0.003906
ETR_-2,0.002045,0.001443,0.000835,0.002641,0.001632,0.001208,0.001280,0.001193,0.001088,0.001963,...,0.002508,0.002210,-0.000116,1.000000,-0.000134,-0.042323,0.005005,0.005022,0.003604,0.003897
ETR_-3,0.002309,0.002033,0.001408,0.000798,0.002615,0.001095,0.001193,0.001265,0.001179,0.001755,...,0.002703,0.002479,-0.042191,-0.000134,1.000000,-0.000140,0.005474,0.005131,0.005109,0.003635
ETR_-4,0.000530,0.002305,0.002039,0.001420,0.000784,0.001113,0.001091,0.001192,0.001271,0.001842,...,0.002620,0.002711,0.002479,-0.042323,-0.000140,1.000000,0.004643,0.006076,0.005768,0.005697
LF_-1,0.024423,0.037536,0.023183,0.025766,0.022986,0.066700,0.067889,0.067709,0.067195,0.073076,...,0.040857,0.040671,0.005099,0.005005,0.005474,0.004643,1.000000,0.947937,0.942827,0.935244
LF_-2,0.024439,0.024325,0.037443,0.022907,0.025485,0.066385,0.066956,0.068174,0.067980,0.069617,...,0.041020,0.041093,0.003747,0.005022,0.005131,0.006076,0.947937,1.000000,0.948039,0.944105
LF_-3,0.023564,0.024183,0.024043,0.037042,0.022293,0.065685,0.066556,0.067158,0.068372,0.068915,...,0.041873,0.041020,0.004060,0.003604,0.005109,0.005768,0.942827,0.948039,1.000000,0.947996
LF_-4,0.032142,0.023112,0.023826,0.023293,0.036163,0.065682,0.065849,0.066753,0.067351,0.068004,...,0.040873,0.041638,0.003906,0.003897,0.003635,0.005697,0.935244,0.944105,0.947996,1.000000