In [2]:
import numpy as np
import pandas as pd

In [48]:
df = pd.read_csv("./../data/processed/tidy_df.csv", index_col=[0, 1, 2])
df.describe()

,EPS,INV,AR,CAPX,GM,SA,ETR,LF
count,53040.000000,53040.000000,53040.000000,53040.000000,53040.000000,53040.000000,53040.000000,53040.000000
mean,66.827855,800.376242,1261.173772,171.093072,507.907409,381.414093,0.353739,16.207476
std,701.697618,7174.810890,8021.502048,2367.920119,3548.375919,2677.572944,6.945108,0.790610
min,-37300.500000,-1248.280315,-2583.170754,-3424.537248,-30368.482179,-1580.555653,-494.716049,11.628080
25%,3.440000,91.289862,179.872083,9.288849,52.674614,39.287031,0.240000,15.668259
50%,15.140000,193.483918,356.085982,24.779200,115.516700,83.215893,0.330664,16.156687
75%,37.640000,413.300901,714.898159,64.640950,223.101503,166.572280,0.414400,16.695472
max,31202.830000,404482.462266,293004.896357,143224.389801,104813.929669,87333.560942,882.000000,22.530918

In [4]:
ai = pd.read_csv("./../assets/y_hats/accuracy_table_i.csv", index_col=[0, 1])
ai.loc[pd.IndexSlice[:, "MAPE-UB"], :].describe()

,y_test,y_hat_rw,y_hat_sarima_br,y_hat_sarima_f,y_hat_sarima_g,y_hat_srw,y_hat_uen_i_tuned_simple,y_hat_ul1_i_tuned_fine,y_hat_ul1_i_tuned_simple,y_hat_ul2_i_tuned_simple,...,y_hat_ml1_i_tuned_fine,y_hat_ml1_i_tuned_simple,y_hat_ml2_i_tuned,y_hat_ml2_i_tuned_simple,y_hat_mlm1,y_hat_mlm2,y_hat_mlm3,y_hat_mlm4,y_hat_mmlp,y_hat_mraf_i_tuned_simple
count,1020.0,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,...,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,0.0,0.579793,0.520454,0.520714,0.527105,0.522570,0.551486,0.555476,0.559925,0.540097,...,0.458928,0.462629,0.543162,0.506380,0.579145,0.590241,0.602192,0.802359,0.559889,0.458680
std,0.0,0.194819,0.203171,0.196642,0.204253,0.199412,0.219370,0.220482,0.220885,0.211414,...,0.235268,0.226560,0.237423,0.228835,0.205451,0.210896,0.210738,0.161706,0.195729,0.194201
min,0.0,0.108712,0.049801,0.079664,0.071814,0.077298,0.078403,0.078403,0.078407,0.078403,...,0.034620,0.037876,0.053897,0.053897,0.051167,0.094949,0.090533,0.185546,0.107655,0.079506
25%,0.0,0.443063,0.372524,0.375289,0.376852,0.378442,0.374747,0.378846,0.381133,0.375782,...,0.258861,0.277043,0.350585,0.318079,0.433350,0.422920,0.438150,0.698596,0.410669,0.305381
50%,0.0,0.583298,0.514272,0.516522,0.521628,0.512606,0.553282,0.559241,0.562916,0.536827,...,0.443917,0.452476,0.555579,0.514212,0.583334,0.597545,0.624763,0.841599,0.551818,0.446347
75%,0.0,0.738256,0.665570,0.669065,0.678658,0.683741,0.721475,0.730319,0.732575,0.699527,...,0.643356,0.634439,0.728180,0.685855,0.734517,0.757975,0.769187,0.928528,0.709208,0.598812
max,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.998699,0.985928

In [5]:
print(df["EPS"].max(), df["EPS"].idxmax())

31202.83 ('東海旅客鉄道', 2012, 'Q1')

In [6]:
ai.loc[pd.IndexSlice[df["EPS"].idxmax()[0], :], :]

                             y_test    y_hat_rw  y_hat_sarima_br  \
東海旅客鉄道 Max_error                0.0  615.740000      3954.899296
       Max_percentage_error     0.0   20.736493        79.543429
       MAE                      0.0  251.500000       623.761050
       MAPE                     0.0    3.195517         9.524587
       MSPE                     0.0   49.003739       581.595388
       MAPE-UB                  0.0    0.582463         0.494408
       MSPE-UB                  0.0    0.514895         0.438236
       Large_error_rate         0.0    0.416667         0.416667

                             y_hat_sarima_f  y_hat_sarima_g    y_hat_srw  \
東海旅客鉄道 Max_error                 912.155787     3324.918856  1039.690000
       Max_percentage_error       23.078273       55.369863    62.076777
       MAE                       179.851220      976.516216   301.334167
       MAPE                        2.783781        7.542774     6.338350
       MSPE                       47.613263      278.133029   325.775804
       MAPE-UB                     0.393722        0.755331     0.459075
       MSPE-UB                     0.349541        0.658989     0.421206
       Large_error_rate            0.333333        0.500000     0.416667

                             y_hat_uen_i_tuned_simple  y_hat_ul1_i_tuned_fine  \
東海旅客鉄道 Max_error                           606.653889              606.653889
       Max_percentage_error                  5.129738                5.129738
       MAE                                 234.164808              234.164808
       MAPE                                  1.278070                1.278070
       MSPE                                  4.212652                4.212652
       MAPE-UB                               0.568822                0.568822
       MSPE-UB                               0.442988                0.442988
       Large_error_rate                      0.333333                0.333333

                             y_hat_ul1_i_tuned_simple  \
東海旅客鉄道 Max_error                           606.653889
       Max_percentage_error                  5.129738
       MAE                                 234.164808
       MAPE                                  1.278070
       MSPE                                  4.212652
       MAPE-UB                               0.568822
       MSPE-UB                               0.442988
       Large_error_rate                      0.333333

                             y_hat_ul2_i_tuned_simple  ...  \
東海旅客鉄道 Max_error                           606.653889  ...
       Max_percentage_error                  5.129738  ...
       MAE                                 234.164808  ...
       MAPE                                  1.278070  ...
       MSPE                                  4.212652  ...
       MAPE-UB                               0.568822  ...
       MSPE-UB                               0.442988  ...
       Large_error_rate                      0.333333  ...

                             y_hat_ml1_i_tuned_fine  y_hat_ml1_i_tuned_simple  \
東海旅客鉄道 Max_error                         726.187907                875.880646
       Max_percentage_error                4.501300                 11.187161
       MAE                               205.001369                258.881851
       MAPE                                0.893284                  2.031755
       MSPE                                2.560917                 14.359795
       MAPE-UB                             0.399747                  0.496810
       MSPE-UB                             0.297781                  0.380826
       Large_error_rate                    0.250000                  0.333333

                             y_hat_ml2_i_tuned  y_hat_ml2_i_tuned_simple  \
東海旅客鉄道 Max_error                    108.072657                150.225440
       Max_percentage_error           2.206789                  1.047848
       MAE                           51.568662                 52.768195
       MAPE                           0.330914                  0.253765
       MSPE                           0.447476                  0.159971
       MAPE-UB                        0.230349                  0.249777
       MSPE-UB                        0.124982                  0.151806
       Large_error_rate               0.083333                  0.083333

                               y_hat_mlm1   y_hat_mlm2   y_hat_mlm3  \
東海旅客鉄道 Max_error             15156.909596  5093.340576  4071.109480
       Max_percentage_error     72.792765    52.380854    68.843259
       MAE                    1705.621803  2129.881219  1757.799990
       MAPE                     11.897978     8.314069    10.307093
       MSPE                    639.027074   250.346058   431.799771
       MAPE-UB                   0.712075     1.000000     1.000000
       MSPE-UB                   0.599705     1.000000     1.000000
       Large_error_rate          0.416667     1.000000     1.000000

                               y_hat_mlm4    y_hat_mmlp  \
東海旅客鉄道 Max_error              9256.704904  11637.991000
       Max_percentage_error    792.763594    461.741043
       MAE                    2301.726869   1797.902382
       MAPE                     71.940009     44.886750
       MSPE                  52515.227624  18039.782992
       MAPE-UB                   0.594143      0.639982
       MSPE-UB                   0.481457      0.537309
       Large_error_rate          0.416667      0.416667

                             y_hat_mraf_i_tuned_simple
東海旅客鉄道 Max_error                           2484.391430
       Max_percentage_error                  68.665220
       MAE                                  490.998451
       MAPE                                   7.429359
       MSPE                                 402.109516
       MAPE-UB                                0.470715
       MSPE-UB                                0.424365
       Large_error_rate                       0.416667

[8 rows x 25 columns]

In [7]:
print(df["EPS"].min(), df["EPS"].idxmin())

-37300.5 ('サンフロンティア不動産', 2008, 'Q3')

In [8]:
ai.loc[pd.IndexSlice[df["EPS"].idxmin()[0], :], :]

                                  y_test    y_hat_rw  y_hat_sarima_br  \
サンフロンティア不動産 Max_error                0.0  120.700000       355.285711
            Max_percentage_error     0.0    6.930796        31.403298
            MAE                      0.0   32.725000        93.951107
            MAPE                     0.0    1.322214         4.973064
            MSPE                     0.0    5.174070        96.789402
            MAPE-UB                  0.0    0.584929         0.751707
            MSPE-UB                  0.0    0.458998         0.667963
            Large_error_rate         0.0    0.333333         0.583333

                                  y_hat_sarima_f  y_hat_sarima_g   y_hat_srw  \
サンフロンティア不動産 Max_error                 115.882060      263.434538  112.090000
            Max_percentage_error        6.054393       22.232805    6.850679
            MAE                        35.948535      107.194807   34.295000
            MAPE                        1.659634        5.841302    1.659992
            MSPE                        6.031284       82.653488    6.609836
            MAPE-UB                     0.666980        0.787337    0.657237
            MSPE-UB                     0.579520        0.727052    0.534876
            Large_error_rate            0.500000        0.666667    0.416667

                                  y_hat_uen_i_tuned_simple  \
サンフロンティア不動産 Max_error                           442.162556
            Max_percentage_error                 29.212015
            MAE                                 181.723751
            MAPE                                  8.164365
            MSPE                                122.871354
            MAPE-UB                               0.921997
            MSPE-UB                               0.917008
            Large_error_rate                      0.916667

                                  y_hat_ul1_i_tuned_fine  \
サンフロンティア不動産 Max_error                         442.162556
            Max_percentage_error               29.212015
            MAE                               181.723752
            MAPE                                8.164365
            MSPE                              122.871354
            MAPE-UB                             0.921997
            MSPE-UB                             0.917008
            Large_error_rate                    0.916667

                                  y_hat_ul1_i_tuned_simple  \
サンフロンティア不動産 Max_error                           442.162556
            Max_percentage_error                 29.212015
            MAE                                 181.723751
            MAPE                                  8.164365
            MSPE                                122.871354
            MAPE-UB                               0.921997
            MSPE-UB                               0.917008
            Large_error_rate                      0.916667

                                  y_hat_ul2_i_tuned_simple  ...  \
サンフロンティア不動産 Max_error                           442.162556  ...
            Max_percentage_error                 29.212015  ...
            MAE                                 181.723751  ...
            MAPE                                  8.164365  ...
            MSPE                                122.871353  ...
            MAPE-UB                               0.921997  ...
            MSPE-UB                               0.917008  ...
            Large_error_rate                      0.916667  ...

                                  y_hat_ml1_i_tuned_fine  \
サンフロンティア不動産 Max_error                          50.259214
            Max_percentage_error                2.988063
            MAE                                26.631379
            MAPE                                1.112500
            MSPE                                1.995314
            MAPE-UB                             0.717802
            MSPE-UB                             0.628733
            Large_error_rate                    0.416667

                                  y_hat_ml1_i_tuned_simple  y_hat_ml2_i_tuned  \
サンフロンティア不動産 Max_error                            60.049577          33.119869
            Max_percentage_error                  3.570129           7.147448
            MAE                                  27.151364          15.186516
            MAPE                                  1.241893           0.969867
            MSPE                                  2.761842           4.506823
            MAPE-UB                               0.721260           0.453678
            MSPE-UB                               0.661044           0.325004
            Large_error_rate                      0.416667           0.166667

                                  y_hat_ml2_i_tuned_simple  y_hat_mlm1  \
サンフロンティア不動産 Max_error                            31.311026  500.876739
            Max_percentage_error                  3.027112   30.634289
            MAE                                  11.970341  258.579565
            MAPE                                  0.580079   10.463827
            MSPE                                  0.981559  172.190156
            MAPE-UB                               0.411153    1.000000
            MSPE-UB                               0.301275    1.000000
            Large_error_rate                      0.083333    1.000000

                                  y_hat_mlm2  y_hat_mlm3  y_hat_mlm4  \
サンフロンティア不動産 Max_error             327.967375  343.396621  605.091821
            Max_percentage_error    6.804185   25.128617   32.647171
            MAE                   129.539058  137.035529  149.317964
            MAPE                    3.570615    5.510155    6.364019
            MSPE                   15.429147   71.678073  112.038844
            MAPE-UB                 0.948949    0.908096    0.923154
            MSPE-UB                 0.929172    0.872960    0.882222
            Large_error_rate        0.916667    0.833333    0.833333

                                  y_hat_mmlp  y_hat_mraf_i_tuned_simple
サンフロンティア不動産 Max_error             133.631550                  71.630500
            Max_percentage_error    7.944801                   6.081150
            MAE                    51.753942                  25.637795
            MAPE                    2.212436                   1.297573
            MSPE                   10.179339                   4.271369
            MAPE-UB                 0.855796                   0.619195
            MSPE-UB                 0.773871                   0.534667
            Large_error_rate        0.500000                   0.416667

[8 rows x 25 columns]

In [49]:
df["EPS"].sort_values().iloc[0:]

企業名            会計年度  四半期
サンフロンティア不動産    2008  Q3    -37300.500000
                     Q4    -14414.110000
ブイ・テクノロジー      2012  Q4    -13265.080000
ソースネクスト        2008  Q3    -13162.920000
マーベラス          2008  Q4    -12869.810000
                                ...
東海旅客鉄道         2012  Q2     25919.902913
エス・エム・エス       2008  Q1     26328.910000
東海旅客鉄道         2008  Q1     28193.440000
プレサンスコーポレーション  2008  Q1     29392.370000
東海旅客鉄道         2012  Q1     31202.830000
Name: EPS, Length: 53040, dtype: float64

In [50]:
tse1 = pd.read_csv("./../data/processed/tidy_tse1.csv", index_col=[0, 1, 2])

In [51]:
tse1[['期中平均株式数［３ヵ月］', '１株当たり利益［３ヵ月］', '棚卸資産', '受取手形・売掛金／売掛金及びその他の短期債権', '資本的支出', '売上総利益［３ヵ月］', '販売費及び一般管理費［３ヵ月］', '法人税等［３ヵ月］']].describe()

,期中平均株式数［３ヵ月］,１株当たり利益［３ヵ月］,棚卸資産,受取手形・売掛金／売掛金及びその他の短期債権,資本的支出,売上総利益［３ヵ月］,販売費及び一般管理費［３ヵ月］,法人税等［３ヵ月］
count,5.777200e+04,57772.000000,5.777200e+04,5.777200e+04,5.777200e+04,5.777200e+04,5.777200e+04,5.777200e+04
mean,1.604495e+08,66.177576,4.582776e+10,6.182541e+10,1.230343e+10,2.033857e+10,1.466088e+10,1.609796e+09
std,4.474589e+08,683.800952,1.437586e+11,1.898491e+11,9.244945e+10,6.949900e+10,4.512451e+10,1.062485e+10
min,-1.602330e+10,-37300.500000,1.000000e+06,1.000000e+06,3.333333e+05,-4.097360e+11,-1.889590e+11,-8.230590e+11
25%,2.005777e+07,3.140000,2.976000e+09,6.182750e+09,3.040000e+08,1.882000e+09,1.420000e+09,8.300000e+07
50%,4.464376e+07,14.660000,9.210000e+09,1.710300e+10,1.082000e+09,4.430000e+09,3.304500e+09,3.220000e+08
75%,1.175955e+08,36.830000,2.896725e+10,4.588150e+10,4.329000e+09,1.368425e+10,1.007925e+10,1.075000e+09
max,1.327322e+10,31202.830000,2.888028e+12,9.714931e+12,5.121960e+12,2.004790e+12,8.779390e+11,7.037010e+11

株式数がマイナスって何?

In [66]:
negative_num_stock_firm = tse1['期中平均株式数［３ヵ月］'][tse1['期中平均株式数［３ヵ月］']<0].index.get_level_values(0).unique()

In [69]:
firm1020 = df.index.get_level_values(0).unique()

In [72]:
firm_list = [i for i in firm1020 if i not in negative_num_stock_firm]

In [74]:
df.loc[pd.IndexSlice[firm_list, :, :], :].describe()

,EPS,INV,AR,CAPX,GM,SA,ETR,LF
count,52156.000000,52156.000000,52156.000000,52156.000000,52156.000000,52156.000000,52156.000000,52156.000000
mean,67.467727,808.786071,1272.915282,173.151578,513.363041,385.509765,0.338515,16.205162
std,707.528642,7234.778194,8087.578909,2387.784061,3577.895891,2699.861698,5.835096,0.793435
min,-37300.500000,0.011063,0.026149,0.000633,-30368.482179,-482.938487,-494.716049,11.628080
25%,3.490000,91.615255,181.896929,9.295766,53.156476,39.602844,0.241129,15.662169
50%,15.230000,193.908125,357.977580,24.741093,115.767654,83.522964,0.330827,16.153621
75%,37.540000,415.648897,717.761375,64.526816,222.789948,166.316806,0.414428,16.693047
max,31202.830000,404482.462266,293004.896357,143224.389801,104813.929669,87333.560942,817.750000,22.530918

In [79]:
ai.loc[pd.IndexSlice[firm_list, "MAPE-UB"], ['y_hat_men_i_tuned', 'y_hat_men_i_tuned_simple', 'y_hat_ml1_i_tuned',
       'y_hat_ml1_i_tuned_fine', 'y_hat_ml1_i_tuned_simple',
       'y_hat_ml2_i_tuned', 'y_hat_ml2_i_tuned_simple', 'y_hat_mlm1',
       'y_hat_mlm2', 'y_hat_mlm3', 'y_hat_mlm4', 'y_hat_mmlp',
       'y_hat_mraf_i_tuned_simple']].describe()

,y_hat_men_i_tuned,y_hat_men_i_tuned_simple,y_hat_ml1_i_tuned,y_hat_ml1_i_tuned_fine,y_hat_ml1_i_tuned_simple,y_hat_ml2_i_tuned,y_hat_ml2_i_tuned_simple,y_hat_mlm1,y_hat_mlm2,y_hat_mlm3,y_hat_mlm4,y_hat_mmlp,y_hat_mraf_i_tuned_simple
count,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000
mean,0.459880,0.453262,0.454585,0.457610,0.461311,0.539923,0.503249,0.578181,0.589142,0.601012,0.801281,0.558493,0.457452
std,0.231492,0.223253,0.222902,0.235536,0.225920,0.236411,0.227540,0.205682,0.210927,0.210614,0.161813,0.195312,0.193798
min,0.037876,0.037876,0.034742,0.034620,0.037876,0.053897,0.053897,0.051167,0.094949,0.090533,0.185546,0.107655,0.079506
25%,0.269110,0.269278,0.269207,0.258574,0.276042,0.344533,0.315414,0.431735,0.422284,0.437219,0.698454,0.409585,0.304906
50%,0.452954,0.448253,0.444278,0.439857,0.450566,0.553466,0.510958,0.582354,0.597554,0.624398,0.840130,0.549466,0.445924
75%,0.632132,0.616897,0.626783,0.641429,0.632226,0.724326,0.679715,0.733975,0.757754,0.767819,0.928096,0.705438,0.597691
max,0.995353,0.988705,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.998699,0.985928

In [77]:
ai.columns

Index(['y_test', 'y_hat_rw', 'y_hat_sarima_br', 'y_hat_sarima_f',
       'y_hat_sarima_g', 'y_hat_srw', 'y_hat_uen_i_tuned_simple',
       'y_hat_ul1_i_tuned_fine', 'y_hat_ul1_i_tuned_simple',
       'y_hat_ul2_i_tuned_simple', 'y_hat_umlp', 'y_hat_umlp_sklearn_default',
       'y_hat_men_i_tuned', 'y_hat_men_i_tuned_simple', 'y_hat_ml1_i_tuned',
       'y_hat_ml1_i_tuned_fine', 'y_hat_ml1_i_tuned_simple',
       'y_hat_ml2_i_tuned', 'y_hat_ml2_i_tuned_simple', 'y_hat_mlm1',
       'y_hat_mlm2', 'y_hat_mlm3', 'y_hat_mlm4', 'y_hat_mmlp',
       'y_hat_mraf_i_tuned_simple'],
      dtype='object')

In [83]:
tse1[["販売費及び一般管理費［３ヵ月］", "法人税等［３ヵ月］"]].describe()

       販売費及び一般管理費［３ヵ月］     法人税等［３ヵ月］
count     5.777200e+04  5.777200e+04
mean      1.466088e+10  1.609796e+09
std       4.512451e+10  1.062485e+10
min      -1.889590e+11 -8.230590e+11
25%       1.420000e+09  8.300000e+07
50%       3.304500e+09  3.220000e+08
75%       1.007925e+10  1.075000e+09
max       8.779390e+11  7.037010e+11

In [82]:
tse1.columns

Index(['決算期（年）', '決算期（月）', '決算期', '連結基準フラグ', '決算種別フラグ', '決算発表日',
       '事業年度開始年月日［３ヵ月］', '事業年度終了年月日', '１株当たり利益［３ヵ月］', '１株当たり利益［累計］',
       '当期純利益（連結）［累計］', '【ＱＴＲ】当期利益', '棚卸資産', '受取手形・売掛金／売掛金及びその他の短期債権', '資本的支出',
       '売上総利益［累計］', '【ＱＴＲ】売上総利益', '販売費及び一般管理費［累計］', '法人税等［累計］',
       '法人税・住民税及び事業税合計／当期税金費用［累計］', '税金等調整前当期純利益［累計］', '税金等調整前当期利益［累計］',
       '【ＱＴＲ】税金等調整前当期利益', '１株当たり税引前利益', '売上高・営業収益［累計］', '【ＱＴＲ】売上高・営業収益',
       '１株当たり売上高', '期末従業員数', '純資産合計／資本合計', '【ＱＴＲ】純資産', '１株当たり純資産',
       '期中平均株式数［累計］', '期中平均株式数［３ヵ月］', '期末発行済株式総数', '自己株式数', '当期純利益（連結）［３ヵ月］',
       '売上総利益［３ヵ月］', '販売費及び一般管理費［３ヵ月］', '法人税等［３ヵ月］', '税金等調整前当期純利益［３ヵ月］',
       '売上高・営業収益［３ヵ月］'],
      dtype='object')