In [1]:
import sys
import numpy as np
import pandas as pd

# import internal modules
sys.path.insert(1, '../src')
from utils.accuracy import MAE, MAPE, MSE, Error, AbsoluteError, PercentageError, AbsolutePercentageError
from execute.accuracy_evaluation import accuracy_table, accuracy_table_i

In [2]:
# read data
tse1 = pd.read_csv("../data/processed/tidy_tse1.csv", index_col=[0, 1, 2])
df = pd.read_csv("../data/processed/tidy_df.csv", index_col=[0, 1, 2])
y_test = pd.read_csv("../assets/y_hats/univariate/y_test.csv", index_col=[0, 1, 2])

y_test_tuned = pd.read_csv("./../assets/y_hats/univariate/y_test-tuned.csv", index_col=[0, 1, 2])

# read y_hat csv
y_hats_all = pd.read_csv("./../assets/y_hats/y_hats_all.csv", index_col=[0, 1, 2])

y_hat_umlp_tuned = pd.read_csv("./../assets/y_hats/univariate/y_hat_umlp-tuned.csv", index_col=[0, 1, 2])
y_hat_umlp_tuned.columns = ['y_hat_umlp_tuned']

In [3]:
tuned_idx = y_hat_umlp_tuned.index
y_hats_all_tuned = pd.concat([y_hats_all.loc[tuned_idx], y_hat_umlp_tuned], axis=1)
y_hats_all_tuned

                    y_test  y_hat_rw  y_hat_sarima_br  y_hat_sarima_f  \
企業名   会計年度 四半期
あらた   2018 Q1   105.420000     69.34       122.565740      122.449521
           Q2    90.440000    105.42        79.897110       79.998967
           Q3   106.240000     90.44       119.386680      119.551232
           Q4    99.220000    106.24        60.222049       59.996949
      2019 Q1   116.850000     99.22       127.203963      125.133255
...                    ...       ...              ...             ...
ナカバヤシ 2019 Q4    24.020000     18.75        26.561118       26.273767
      2020 Q1     6.920000     24.02         3.712785        3.091105
           Q2     9.970000      6.92        14.961625       15.418836
           Q3    18.020000      9.97        16.189976       17.786525
           Q4    27.132261     18.02        24.093658       23.849988

                y_hat_sarima_g  y_hat_umlp  y_hat_mlm1  y_hat_mlm2  \
企業名   会計年度 四半期
あらた   2018 Q1       130.595361  111.257810  142.213501  113.490222
           Q2        94.544504   84.751390   92.463386  157.027451
           Q3       119.287623  114.484960  118.419913   84.545219
           Q4        65.424073   79.355910   72.589673  111.753597
      2019 Q1       126.004465  113.642660   98.036624  126.181789
...                        ...         ...         ...         ...
ナカバヤシ 2019 Q4        26.200703   27.199738   15.183136   25.598650
      2020 Q1         9.523660    6.141288    1.975165    4.791292
           Q2        15.290302    9.670843   18.051315   16.485760
           Q3        17.751937   17.257587   23.277572   10.348492
           Q4        24.889223   27.261902   20.910173   26.448377

                y_hat_mlm3  y_hat_mlm4  y_hat_umlp_tuned
企業名   会計年度 四半期
あらた   2018 Q1   117.339606  263.859095        113.819885
           Q2   147.870649  186.013135         35.870438
           Q3    84.910297  -90.797436        111.682240
           Q4    83.042883   43.663635         82.335860
      2019 Q1   135.395355  137.056577        101.692580
...                    ...         ...               ...
ナカバヤシ 2019 Q4    27.012832   23.958515         18.433937
      2020 Q1     6.214081   13.743974          4.864047
           Q2    17.309629   46.440608          8.805465
           Q3     9.545515   60.834186         20.328085
           Q4    26.414833   30.068649         27.398205

[3600 rows x 11 columns]

In [4]:
indicators = {"MAPE": MAPE}

In [5]:
a = accuracy_table(y_hats_all_tuned["y_test"], y_hats_all_tuned, indicators)
a

,y_test,y_hat_rw,y_hat_sarima_br,y_hat_sarima_f,y_hat_sarima_g,y_hat_umlp,y_hat_mlm1,y_hat_mlm2,y_hat_mlm3,y_hat_mlm4,y_hat_umlp_tuned
MAPE,0.0,4.632464,3.40869,3.067016,4.603534,6.791134,5.412545,5.668356,6.39286,22.41223,5.518826

全企業平均MAPEでみると、umlpはtuneすることで改善している。

In [6]:
ai = accuracy_table_i(y_hats_all_tuned["y_test"], y_hats_all_tuned, indicators)
ai

,,y_test,y_hat_rw,y_hat_sarima_br,y_hat_sarima_f,y_hat_sarima_g,y_hat_umlp,y_hat_mlm1,y_hat_mlm2,y_hat_mlm3,y_hat_mlm4,y_hat_umlp_tuned
あらた,MAPE,0.0,0.326915,0.209451,0.199988,0.202024,0.144319,0.200535,0.298360,0.273272,1.057403,0.208408
いすゞ自動車,MAPE,0.0,1.033565,0.674522,0.596406,0.769031,0.627432,1.406949,0.509453,0.529282,3.667137,0.788857
いなげや,MAPE,0.0,1.923584,0.933579,1.239337,1.253766,1.545034,2.690945,1.532201,1.594809,2.358227,1.341612
かどや製油,MAPE,0.0,0.973943,0.612928,0.585215,0.717560,0.756591,0.964528,0.372779,0.348536,1.999852,0.829407
きんでん,MAPE,0.0,1.548829,0.151986,0.132039,0.169481,0.308766,0.184258,0.283411,0.248188,0.438089,0.235014
...,...,...,...,...,...,...,...,...,...,...,...,...
トーヨーカネツ,MAPE,0.0,1.015039,1.134532,1.165661,1.090821,1.112939,2.462834,2.477626,4.044893,42.104464,0.931979
ドウシシャ,MAPE,0.0,1.349040,0.377019,0.404820,0.496414,0.459693,0.541745,0.463355,0.480165,1.318989,0.524234
ナイス,MAPE,0.0,3.053385,2.971045,3.462197,1.875018,1.464434,10.572903,9.605226,12.062289,21.882011,1.207602
ナカノフドー建設,MAPE,0.0,3.865303,2.028273,1.226834,2.165956,0.721285,3.742798,2.704813,2.528175,6.447280,1.823624
ナカバヤシ,MAPE,0.0,1.151663,0.381984,0.382537,0.410631,0.603267,0.657698,0.457217,0.500065,3.714319,0.681729

In [7]:
ai.describe()

,y_test,y_hat_rw,y_hat_sarima_br,y_hat_sarima_f,y_hat_sarima_g,y_hat_umlp,y_hat_mlm1,y_hat_mlm2,y_hat_mlm3,y_hat_mlm4,y_hat_umlp_tuned
count,300.0,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,0.0,4.632464,3.408690,3.067016,4.603534,6.791134,5.412545,5.668356,6.392860,22.412230,5.518826
std,0.0,26.953409,13.633688,14.053122,19.037207,39.168003,19.121213,18.604377,24.102070,145.561499,16.739690
min,0.0,0.123713,0.107931,0.097180,0.105856,0.134809,0.108896,0.138529,0.156677,0.266479,0.165226
25%,0.0,0.651816,0.445522,0.467595,0.510343,0.594734,0.628482,0.607727,0.619790,1.468957,0.606175
50%,0.0,1.289371,0.924229,0.888179,0.996223,1.113797,1.240105,1.330104,1.328983,3.724123,1.146566
75%,0.0,2.414340,1.735282,1.555427,2.115693,2.375506,2.589672,2.836544,2.958713,10.151756,2.342689
max,0.0,367.540924,164.352736,172.733304,217.715085,619.460421,221.832211,151.442378,217.532768,2427.964819,151.783176

企業ごとに見れば、tuneしてないのに比べて最大MAPE企業のMAPEが小さい。tuneすること(もしくはearly stoppingによって)過学習を防いだ?

In [8]:
#Upper bound

logを見る限り、10000 epochまでやっているケース(時間かかる)は、optunaによってかなり小さいlrが選択されているとき。

--> search spaceを大きめに設定するとかで改善できるかも

10000 epoch までやってしまっているモデルの予測はヘタクソかどうかを個別に確認する.