In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("./../data/processed/tidy_df.csv", index_col=[0, 1, 2])
df.describe()

,EPS,INV,AR,CAPX,GM,SA,ETR,LF
count,53040.000000,53040.000000,53040.000000,53040.000000,53040.000000,53040.000000,53040.000000,53040.000000
mean,66.827855,800.376242,1261.173772,171.093072,507.907409,381.414093,0.353739,16.207476
std,701.697618,7174.810890,8021.502048,2367.920119,3548.375919,2677.572944,6.945108,0.790610
min,-37300.500000,-1248.280315,-2583.170754,-3424.537248,-30368.482179,-1580.555653,-494.716049,11.628080
25%,3.440000,91.289862,179.872083,9.288849,52.674614,39.287031,0.240000,15.668259
50%,15.140000,193.483918,356.085982,24.779200,115.516700,83.215893,0.330664,16.156687
75%,37.640000,413.300901,714.898159,64.640950,223.101503,166.572280,0.414400,16.695472
max,31202.830000,404482.462266,293004.896357,143224.389801,104813.929669,87333.560942,882.000000,22.530918

In [4]:
ai = pd.read_csv("./../assets/y_hats/accuracy_table_i.csv", index_col=[0, 1])
ai.loc[pd.IndexSlice[:, "MAPE-UB"], :].describe()

,y_test,y_hat_rw,y_hat_sarima_br,y_hat_sarima_f,y_hat_sarima_g,y_hat_srw,y_hat_uen_i_tuned_simple,y_hat_ul1_i_tuned_fine,y_hat_ul1_i_tuned_simple,y_hat_ul2_i_tuned_simple,...,y_hat_ml1_i_tuned_fine,y_hat_ml1_i_tuned_simple,y_hat_ml2_i_tuned,y_hat_ml2_i_tuned_simple,y_hat_mlm1,y_hat_mlm2,y_hat_mlm3,y_hat_mlm4,y_hat_mmlp,y_hat_mraf_i_tuned_simple
count,1020.0,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,...,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,0.0,0.579793,0.520454,0.520714,0.527105,0.522570,0.551486,0.555476,0.559925,0.540097,...,0.458928,0.462629,0.543162,0.506380,0.579145,0.590241,0.602192,0.802359,0.559889,0.458680
std,0.0,0.194819,0.203171,0.196642,0.204253,0.199412,0.219370,0.220482,0.220885,0.211414,...,0.235268,0.226560,0.237423,0.228835,0.205451,0.210896,0.210738,0.161706,0.195729,0.194201
min,0.0,0.108712,0.049801,0.079664,0.071814,0.077298,0.078403,0.078403,0.078407,0.078403,...,0.034620,0.037876,0.053897,0.053897,0.051167,0.094949,0.090533,0.185546,0.107655,0.079506
25%,0.0,0.443063,0.372524,0.375289,0.376852,0.378442,0.374747,0.378846,0.381133,0.375782,...,0.258861,0.277043,0.350585,0.318079,0.433350,0.422920,0.438150,0.698596,0.410669,0.305381
50%,0.0,0.583298,0.514272,0.516522,0.521628,0.512606,0.553282,0.559241,0.562916,0.536827,...,0.443917,0.452476,0.555579,0.514212,0.583334,0.597545,0.624763,0.841599,0.551818,0.446347
75%,0.0,0.738256,0.665570,0.669065,0.678658,0.683741,0.721475,0.730319,0.732575,0.699527,...,0.643356,0.634439,0.728180,0.685855,0.734517,0.757975,0.769187,0.928528,0.709208,0.598812
max,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.998699,0.985928

In [5]:
print(df["EPS"].max(), df["EPS"].idxmax())

31202.83 ('東海旅客鉄道', 2012, 'Q1')

In [6]:
ai.loc[pd.IndexSlice[df["EPS"].idxmax()[0], :], :]

                             y_test    y_hat_rw  y_hat_sarima_br  \
東海旅客鉄道 Max_error                0.0  615.740000      3954.899296
       Max_percentage_error     0.0   20.736493        79.543429
       MAE                      0.0  251.500000       623.761050
       MAPE                     0.0    3.195517         9.524587
       MSPE                     0.0   49.003739       581.595388
       MAPE-UB                  0.0    0.582463         0.494408
       MSPE-UB                  0.0    0.514895         0.438236
       Large_error_rate         0.0    0.416667         0.416667

                             y_hat_sarima_f  y_hat_sarima_g    y_hat_srw  \
東海旅客鉄道 Max_error                 912.155787     3324.918856  1039.690000
       Max_percentage_error       23.078273       55.369863    62.076777
       MAE                       179.851220      976.516216   301.334167
       MAPE                        2.783781        7.542774     6.338350
       MSPE                       47.613263      278.133029   325.775804
       MAPE-UB                     0.393722        0.755331     0.459075
       MSPE-UB                     0.349541        0.658989     0.421206
       Large_error_rate            0.333333        0.500000     0.416667

                             y_hat_uen_i_tuned_simple  y_hat_ul1_i_tuned_fine  \
東海旅客鉄道 Max_error                           606.653889              606.653889
       Max_percentage_error                  5.129738                5.129738
       MAE                                 234.164808              234.164808
       MAPE                                  1.278070                1.278070
       MSPE                                  4.212652                4.212652
       MAPE-UB                               0.568822                0.568822
       MSPE-UB                               0.442988                0.442988
       Large_error_rate                      0.333333                0.333333

                             y_hat_ul1_i_tuned_simple  \
東海旅客鉄道 Max_error                           606.653889
       Max_percentage_error                  5.129738
       MAE                                 234.164808
       MAPE                                  1.278070
       MSPE                                  4.212652
       MAPE-UB                               0.568822
       MSPE-UB                               0.442988
       Large_error_rate                      0.333333

                             y_hat_ul2_i_tuned_simple  ...  \
東海旅客鉄道 Max_error                           606.653889  ...
       Max_percentage_error                  5.129738  ...
       MAE                                 234.164808  ...
       MAPE                                  1.278070  ...
       MSPE                                  4.212652  ...
       MAPE-UB                               0.568822  ...
       MSPE-UB                               0.442988  ...
       Large_error_rate                      0.333333  ...

                             y_hat_ml1_i_tuned_fine  y_hat_ml1_i_tuned_simple  \
東海旅客鉄道 Max_error                         726.187907                875.880646
       Max_percentage_error                4.501300                 11.187161
       MAE                               205.001369                258.881851
       MAPE                                0.893284                  2.031755
       MSPE                                2.560917                 14.359795
       MAPE-UB                             0.399747                  0.496810
       MSPE-UB                             0.297781                  0.380826
       Large_error_rate                    0.250000                  0.333333

                             y_hat_ml2_i_tuned  y_hat_ml2_i_tuned_simple  \
東海旅客鉄道 Max_error                    108.072657                150.225440
       Max_percentage_error           2.206789                  1.047848
       MAE                           51.568662                 52.768195
       MAPE                           0.330914                  0.253765
       MSPE                           0.447476                  0.159971
       MAPE-UB                        0.230349                  0.249777
       MSPE-UB                        0.124982                  0.151806
       Large_error_rate               0.083333                  0.083333

                               y_hat_mlm1   y_hat_mlm2   y_hat_mlm3  \
東海旅客鉄道 Max_error             15156.909596  5093.340576  4071.109480
       Max_percentage_error     72.792765    52.380854    68.843259
       MAE                    1705.621803  2129.881219  1757.799990
       MAPE                     11.897978     8.314069    10.307093
       MSPE                    639.027074   250.346058   431.799771
       MAPE-UB                   0.712075     1.000000     1.000000
       MSPE-UB                   0.599705     1.000000     1.000000
       Large_error_rate          0.416667     1.000000     1.000000

                               y_hat_mlm4    y_hat_mmlp  \
東海旅客鉄道 Max_error              9256.704904  11637.991000
       Max_percentage_error    792.763594    461.741043
       MAE                    2301.726869   1797.902382
       MAPE                     71.940009     44.886750
       MSPE                  52515.227624  18039.782992
       MAPE-UB                   0.594143      0.639982
       MSPE-UB                   0.481457      0.537309
       Large_error_rate          0.416667      0.416667

                             y_hat_mraf_i_tuned_simple
東海旅客鉄道 Max_error                           2484.391430
       Max_percentage_error                  68.665220
       MAE                                  490.998451
       MAPE                                   7.429359
       MSPE                                 402.109516
       MAPE-UB                                0.470715
       MSPE-UB                                0.424365
       Large_error_rate                       0.416667

[8 rows x 25 columns]

In [7]:
print(df["EPS"].min(), df["EPS"].idxmin())

-37300.5 ('サンフロンティア不動産', 2008, 'Q3')

In [8]:
ai.loc[pd.IndexSlice[df["EPS"].idxmin()[0], :], :]

                                  y_test    y_hat_rw  y_hat_sarima_br  \
サンフロンティア不動産 Max_error                0.0  120.700000       355.285711
            Max_percentage_error     0.0    6.930796        31.403298
            MAE                      0.0   32.725000        93.951107
            MAPE                     0.0    1.322214         4.973064
            MSPE                     0.0    5.174070        96.789402
            MAPE-UB                  0.0    0.584929         0.751707
            MSPE-UB                  0.0    0.458998         0.667963
            Large_error_rate         0.0    0.333333         0.583333

                                  y_hat_sarima_f  y_hat_sarima_g   y_hat_srw  \
サンフロンティア不動産 Max_error                 115.882060      263.434538  112.090000
            Max_percentage_error        6.054393       22.232805    6.850679
            MAE                        35.948535      107.194807   34.295000
            MAPE                        1.659634        5.841302    1.659992
            MSPE                        6.031284       82.653488    6.609836
            MAPE-UB                     0.666980        0.787337    0.657237
            MSPE-UB                     0.579520        0.727052    0.534876
            Large_error_rate            0.500000        0.666667    0.416667

                                  y_hat_uen_i_tuned_simple  \
サンフロンティア不動産 Max_error                           442.162556
            Max_percentage_error                 29.212015
            MAE                                 181.723751
            MAPE                                  8.164365
            MSPE                                122.871354
            MAPE-UB                               0.921997
            MSPE-UB                               0.917008
            Large_error_rate                      0.916667

                                  y_hat_ul1_i_tuned_fine  \
サンフロンティア不動産 Max_error                         442.162556
            Max_percentage_error               29.212015
            MAE                               181.723752
            MAPE                                8.164365
            MSPE                              122.871354
            MAPE-UB                             0.921997
            MSPE-UB                             0.917008
            Large_error_rate                    0.916667

                                  y_hat_ul1_i_tuned_simple  \
サンフロンティア不動産 Max_error                           442.162556
            Max_percentage_error                 29.212015
            MAE                                 181.723751
            MAPE                                  8.164365
            MSPE                                122.871354
            MAPE-UB                               0.921997
            MSPE-UB                               0.917008
            Large_error_rate                      0.916667

                                  y_hat_ul2_i_tuned_simple  ...  \
サンフロンティア不動産 Max_error                           442.162556  ...
            Max_percentage_error                 29.212015  ...
            MAE                                 181.723751  ...
            MAPE                                  8.164365  ...
            MSPE                                122.871353  ...
            MAPE-UB                               0.921997  ...
            MSPE-UB                               0.917008  ...
            Large_error_rate                      0.916667  ...

                                  y_hat_ml1_i_tuned_fine  \
サンフロンティア不動産 Max_error                          50.259214
            Max_percentage_error                2.988063
            MAE                                26.631379
            MAPE                                1.112500
            MSPE                                1.995314
            MAPE-UB                             0.717802
            MSPE-UB                             0.628733
            Large_error_rate                    0.416667

                                  y_hat_ml1_i_tuned_simple  y_hat_ml2_i_tuned  \
サンフロンティア不動産 Max_error                            60.049577          33.119869
            Max_percentage_error                  3.570129           7.147448
            MAE                                  27.151364          15.186516
            MAPE                                  1.241893           0.969867
            MSPE                                  2.761842           4.506823
            MAPE-UB                               0.721260           0.453678
            MSPE-UB                               0.661044           0.325004
            Large_error_rate                      0.416667           0.166667

                                  y_hat_ml2_i_tuned_simple  y_hat_mlm1  \
サンフロンティア不動産 Max_error                            31.311026  500.876739
            Max_percentage_error                  3.027112   30.634289
            MAE                                  11.970341  258.579565
            MAPE                                  0.580079   10.463827
            MSPE                                  0.981559  172.190156
            MAPE-UB                               0.411153    1.000000
            MSPE-UB                               0.301275    1.000000
            Large_error_rate                      0.083333    1.000000

                                  y_hat_mlm2  y_hat_mlm3  y_hat_mlm4  \
サンフロンティア不動産 Max_error             327.967375  343.396621  605.091821
            Max_percentage_error    6.804185   25.128617   32.647171
            MAE                   129.539058  137.035529  149.317964
            MAPE                    3.570615    5.510155    6.364019
            MSPE                   15.429147   71.678073  112.038844
            MAPE-UB                 0.948949    0.908096    0.923154
            MSPE-UB                 0.929172    0.872960    0.882222
            Large_error_rate        0.916667    0.833333    0.833333

                                  y_hat_mmlp  y_hat_mraf_i_tuned_simple
サンフロンティア不動産 Max_error             133.631550                  71.630500
            Max_percentage_error    7.944801                   6.081150
            MAE                    51.753942                  25.637795
            MAPE                    2.212436                   1.297573
            MSPE                   10.179339                   4.271369
            MAPE-UB                 0.855796                   0.619195
            MSPE-UB                 0.773871                   0.534667
            Large_error_rate        0.500000                   0.416667

[8 rows x 25 columns]

In [13]:
df["EPS"].sort_values().iloc[0:]

企業名          会計年度  四半期
サンフロンティア不動産  2008  Q3    -37300.50
                   Q4    -14414.11
ブイ・テクノロジー    2012  Q4    -13265.08
ソースネクスト      2008  Q3    -13162.92
マーベラス        2008  Q4    -12869.81
                            ...
ミマキエンジニアリング  2011  Q3      -966.52
ｅＢＡＳＥ        2010  Q3      -962.98
エムスリー        2009  Q1      -955.27
クボテック        2012  Q3      -954.47
三菱製鋼         2019  Q2      -917.09
Name: EPS, Length: 100, dtype: float64

In [18]:
tse1 = pd.read_csv("./../data/processed/tidy_tse1.csv", index_col=[0, 1, 2])

In [21]:
tse1[['期中平均株式数［３ヵ月］', '１株当たり利益［３ヵ月］', '棚卸資産', '受取手形・売掛金／売掛金及びその他の短期債権', '資本的支出', '売上総利益［３ヵ月］', '販売費及び一般管理費［３ヵ月］', '法人税等［３ヵ月］']].describe()

,期中平均株式数［３ヵ月］,１株当たり利益［３ヵ月］,棚卸資産,受取手形・売掛金／売掛金及びその他の短期債権,資本的支出,売上総利益［３ヵ月］,販売費及び一般管理費［３ヵ月］,法人税等［３ヵ月］
count,5.777200e+04,57772.000000,5.777200e+04,5.777200e+04,5.777200e+04,5.777200e+04,5.777200e+04,5.777200e+04
mean,1.604495e+08,66.177576,4.582776e+10,6.182541e+10,1.230343e+10,2.033857e+10,1.466088e+10,1.609796e+09
std,4.474589e+08,683.800952,1.437586e+11,1.898491e+11,9.244945e+10,6.949900e+10,4.512451e+10,1.062485e+10
min,-1.602330e+10,-37300.500000,1.000000e+06,1.000000e+06,3.333333e+05,-4.097360e+11,-1.889590e+11,-8.230590e+11
25%,2.005777e+07,3.140000,2.976000e+09,6.182750e+09,3.040000e+08,1.882000e+09,1.420000e+09,8.300000e+07
50%,4.464376e+07,14.660000,9.210000e+09,1.710300e+10,1.082000e+09,4.430000e+09,3.304500e+09,3.220000e+08
75%,1.175955e+08,36.830000,2.896725e+10,4.588150e+10,4.329000e+09,1.368425e+10,1.007925e+10,1.075000e+09
max,1.327322e+10,31202.830000,2.888028e+12,9.714931e+12,5.121960e+12,2.004790e+12,8.779390e+11,7.037010e+11

株式数がマイナスって何?

In [34]:
tse1_unitchanged = pd.read_csv("./../data/processed/tse1_unitchanged.csv", index_col=[0, 1, 2])

In [35]:
tse1_unitchanged

                               決算期  連結基準フラグ  決算種別フラグ       決算発表日  \
企業名         決算期（年） 決算期（月）
あい　ホールディングス 2007   6       2007/06        1       10  2007-08-24
                   9       2007/09        1       21  2007-11-15
                   12      2007/12        1       22  2008-02-27
            2008   3       2008/03        1       23  2008-05-23
                   6       2008/06        1       10  2008-08-22
...                            ...      ...      ...         ...
ｇｕｍｉ        2020   1       2020/01        1       23  2020-03-06
                   4       2020/04        1       10  2020-06-09
                   7       2020/07        1       21  2020-09-10
                   10      2020/10        1       22  2020-12-10
            2021   1       2021/01        1       23  2021-03-12

                          事業年度開始年月日［３ヵ月］   事業年度終了年月日  １株当たり利益［３ヵ月］  \
企業名         決算期（年） 決算期（月）
あい　ホールディングス 2007   6                 NaN  2007-06-30           NaN
                   9          2007-07-01  2007-09-30          7.16
                   12                NaN  2007-12-31           NaN
            2008   3                 NaN  2008-03-31           NaN
                   6                 NaN  2008-06-30           NaN
...                                  ...         ...           ...
ｇｕｍｉ        2020   1          2019-11-01  2020-01-31         15.34
                   4          2020-02-01  2020-04-30         44.05
                   7          2020-05-01  2020-07-31         29.87
                   10         2020-08-01  2020-10-31          3.42
            2021   1          2020-11-01  2021-01-31         19.63

                           １株当たり利益［累計］  当期純利益（連結）［累計］     【ＱＴＲ】当期利益  ...  \
企業名         決算期（年） 決算期（月）                                            ...
あい　ホールディングス 2007   6             18.13            NaN           NaN  ...
                   9              7.16            NaN  3.930000e+08  ...
                   12             2.05            NaN -2.810000e+08  ...
            2008   3              7.48            NaN  2.990000e+08  ...
                   6             11.10            NaN  1.980000e+08  ...
...                                ...            ...           ...  ...
ｇｕｍｉ        2020   1             14.24   2.290000e+08  4.620000e+08  ...
                   4             58.32   1.472000e+09  1.328000e+09  ...
                   7             29.87   8.930000e+08  9.010000e+08  ...
                   10            33.27   9.880000e+08  1.030000e+08  ...
            2021   1             52.90   1.570000e+09  5.940000e+08  ...

                           【ＱＴＲ】売上高・営業収益  １株当たり売上高  期末従業員数    純資産合計／資本合計  \
企業名         決算期（年） 決算期（月）
あい　ホールディングス 2007   6                 NaN    828.46   742.0  2.171700e+10
                   9        6.141000e+09       NaN     NaN  2.131600e+10
                   12       5.773000e+09    433.61   744.0  2.093900e+10
            2008   3        6.074000e+09    436.42     NaN  2.026900e+10
                   6        5.686000e+09    430.90   772.0  2.050700e+10
...                                  ...       ...     ...           ...
ｇｕｍｉ        2020   1        5.680000e+09    644.74     NaN  1.404000e+10
                   4        5.260000e+09    657.98   852.0  1.516900e+10
                   7        5.351000e+09    708.99     NaN  1.587900e+10
                   10       4.482000e+09    651.02     NaN  1.604900e+10
            2021   1        5.012000e+09    654.96     NaN  1.671100e+10

                               【ＱＴＲ】純資産  １株当たり純資産  期中平均株式数［累計］  期中平均株式数［３ヵ月］  \
企業名         決算期（年） 決算期（月）
あい　ホールディングス 2007   6                NaN    395.18   54955303.0           NaN
                   9       2.131600e+10    387.90          NaN           NaN
                   12      2.093900e+10    381.04   54953000.0           NaN
            2008   3       2.026900e+10    369.22   54955716.0           NaN
                   6       2.050700e+10    373.55   54941000.0           NaN
...                                 ...       ...          ...           ...
ｇｕｍｉ        2020   1       1.404000e+10       NaN   30124828.0           NaN
                   4       1.516900e+10    470.93   30133166.0           NaN
                   7       1.587900e+10       NaN   30189380.0    30189380.0
                   10      1.604900e+10       NaN   30208191.0           NaN
            2021   1       1.671100e+10       NaN   30220748.0           NaN

                            期末発行済株式総数      自己株式数
企業名         決算期（年） 決算期（月）
あい　ホールディングス 2007   6       56590410.0  1635869.0
                   9              NaN        NaN
                   12      56590410.0  1637131.0
            2008   3              NaN        NaN
                   6       56590410.0  1692988.0
...                               ...        ...
ｇｕｍｉ        2020   1       31119500.0   980000.0
                   4       31169400.0   980000.0
                   7       31169400.0   980039.0
                   10      31225900.0   980039.0
            2021   1       31225900.0   980039.0

[143657 rows x 33 columns]

In [27]:
tse1_unitchanged[['期中平均株式数［３ヵ月］', '１株当たり利益［３ヵ月］', '棚卸資産', '受取手形・売掛金／売掛金及びその他の短期債権', '資本的支出', '売上総利益［３ヵ月］', '販売費及び一般管理費［３ヵ月］', '法人税等［３ヵ月］']].describe()

KeyError: "['売上総利益［３ヵ月］', '販売費及び一般管理費［３ヵ月］', '法人税等［３ヵ月］'] not in index"

In [31]:
tse1_unitchanged['期中平均株式数［累計］'].isna().sum()

16918

In [32]:
tse1_unitchanged

                               決算期  連結基準フラグ  決算種別フラグ       決算発表日  \
企業名         決算期（年） 決算期（月）
あい　ホールディングス 2007   6       2007/06        1       10  2007-08-24
                   9       2007/09        1       21  2007-11-15
                   12      2007/12        1       22  2008-02-27
            2008   3       2008/03        1       23  2008-05-23
                   6       2008/06        1       10  2008-08-22
...                            ...      ...      ...         ...
ｇｕｍｉ        2020   1       2020/01        1       23  2020-03-06
                   4       2020/04        1       10  2020-06-09
                   7       2020/07        1       21  2020-09-10
                   10      2020/10        1       22  2020-12-10
            2021   1       2021/01        1       23  2021-03-12

                          事業年度開始年月日［３ヵ月］   事業年度終了年月日  １株当たり利益［３ヵ月］  \
企業名         決算期（年） 決算期（月）
あい　ホールディングス 2007   6                 NaN  2007-06-30           NaN
                   9          2007-07-01  2007-09-30          7.16
                   12                NaN  2007-12-31           NaN
            2008   3                 NaN  2008-03-31           NaN
                   6                 NaN  2008-06-30           NaN
...                                  ...         ...           ...
ｇｕｍｉ        2020   1          2019-11-01  2020-01-31         15.34
                   4          2020-02-01  2020-04-30         44.05
                   7          2020-05-01  2020-07-31         29.87
                   10         2020-08-01  2020-10-31          3.42
            2021   1          2020-11-01  2021-01-31         19.63

                           １株当たり利益［累計］  当期純利益（連結）［累計］     【ＱＴＲ】当期利益  ...  \
企業名         決算期（年） 決算期（月）                                            ...
あい　ホールディングス 2007   6             18.13            NaN           NaN  ...
                   9              7.16            NaN  3.930000e+08  ...
                   12             2.05            NaN -2.810000e+08  ...
            2008   3              7.48            NaN  2.990000e+08  ...
                   6             11.10            NaN  1.980000e+08  ...
...                                ...            ...           ...  ...
ｇｕｍｉ        2020   1             14.24   2.290000e+08  4.620000e+08  ...
                   4             58.32   1.472000e+09  1.328000e+09  ...
                   7             29.87   8.930000e+08  9.010000e+08  ...
                   10            33.27   9.880000e+08  1.030000e+08  ...
            2021   1             52.90   1.570000e+09  5.940000e+08  ...

                           【ＱＴＲ】売上高・営業収益  １株当たり売上高  期末従業員数    純資産合計／資本合計  \
企業名         決算期（年） 決算期（月）
あい　ホールディングス 2007   6                 NaN    828.46   742.0  2.171700e+10
                   9        6.141000e+09       NaN     NaN  2.131600e+10
                   12       5.773000e+09    433.61   744.0  2.093900e+10
            2008   3        6.074000e+09    436.42     NaN  2.026900e+10
                   6        5.686000e+09    430.90   772.0  2.050700e+10
...                                  ...       ...     ...           ...
ｇｕｍｉ        2020   1        5.680000e+09    644.74     NaN  1.404000e+10
                   4        5.260000e+09    657.98   852.0  1.516900e+10
                   7        5.351000e+09    708.99     NaN  1.587900e+10
                   10       4.482000e+09    651.02     NaN  1.604900e+10
            2021   1        5.012000e+09    654.96     NaN  1.671100e+10

                               【ＱＴＲ】純資産  １株当たり純資産  期中平均株式数［累計］  期中平均株式数［３ヵ月］  \
企業名         決算期（年） 決算期（月）
あい　ホールディングス 2007   6                NaN    395.18   54955303.0           NaN
                   9       2.131600e+10    387.90          NaN           NaN
                   12      2.093900e+10    381.04   54953000.0           NaN
            2008   3       2.026900e+10    369.22   54955716.0           NaN
                   6       2.050700e+10    373.55   54941000.0           NaN
...                                 ...       ...          ...           ...
ｇｕｍｉ        2020   1       1.404000e+10       NaN   30124828.0           NaN
                   4       1.516900e+10    470.93   30133166.0           NaN
                   7       1.587900e+10       NaN   30189380.0    30189380.0
                   10      1.604900e+10       NaN   30208191.0           NaN
            2021   1       1.671100e+10       NaN   30220748.0           NaN

                            期末発行済株式総数      自己株式数
企業名         決算期（年） 決算期（月）
あい　ホールディングス 2007   6       56590410.0  1635869.0
                   9              NaN        NaN
                   12      56590410.0  1637131.0
            2008   3              NaN        NaN
                   6       56590410.0  1692988.0
...                               ...        ...
ｇｕｍｉ        2020   1       31119500.0   980000.0
                   4       31169400.0   980000.0
                   7       31169400.0   980039.0
                   10      31225900.0   980039.0
            2021   1       31225900.0   980039.0

[143657 rows x 33 columns]

In [39]:
df = pd.read_csv("./../data/processed/tse1_unitchanged.csv", index_col=[0, 1, 2])

print("# firm: ", len(df.loc[pd.IndexSlice[:, 2008:, :], :].index.get_level_values(0).unique()))

# * 2008Q1~ 6, 9, 12, 3月に四半期報告する企業に絞る
year_range = np.arange(2008, 2021)
month_range = [6, 9, 12, 3]

# check if firm recorded in all quater 
# start from firm recorded in 2008Q1
recorded_firm_from_2008 = set(df.loc[pd.IndexSlice[:, 2008, 6], :].index.get_level_values("企業名").unique())

for i in year_range:
    for j in month_range:
        if j == 3: # if Mar, +1 year
            i += 1
        recorded_firm_from_2008 = recorded_firm_from_2008 & set(df.loc[pd.IndexSlice[:, i, j], :].index.get_level_values("企業名").unique())

df = df.loc[pd.IndexSlice[recorded_firm_from_2008, :, :], :] # 遡るためrecorded_firm_from_2008の企業の全期間 : のデータフレームを作成

# firm:  2118

TypeError: unhashable type: 'set'

In [40]:
recorded_firm_from_2008

{'愛眼',
 '古河機械金属',
 'リンナイ',
 'コクヨ',
 'ミズノ',
 '東京一番フーズ',
 'ＯＵＧホールディングス',
 'タツモ',
 '東テク',
 '日本電子材料',
 '昭光通商',
 'サカイオーベックス',
 'ダイワボウホールディングス',
 '物語コーポレーション',
 '田谷',
 'ナイス',
 '岡谷電機産業',
 '大同工業',
 'ジェイテクト',
 '正興電機製作所',
 '日新電機',
 'マキタ',
 '日機装',
 '豊田合成',
 'イチケン',
 'さくらインターネット',
 '前沢化成工業',
 '日本ケミコン',
 'ダイキン工業',
 '上新電機',
 'ティアック',
 'チタン工業',
 '朝日ネット',
 'リソルホールディングス',
 '堀場製作所',
 'クニミネ工業',
 '新京成電鉄',
 'コネクシオ',
 'ＤＭＧ森精機',
 'ｅＢＡＳＥ',
 '東洋建設',
 '共英製鋼',
 '古河電気工業',
 '日本金属',
 'アドバンテッジリスクマネジメン',
 'アルペン',
 'トレンドマイクロ',
 '原田工業',
 '木曽路',
 'あい\u3000ホールディングス',
 'アドバネクス',
 '中山製鋼所',
 '名糖産業',
 '大和工業',
 '大和ハウス工業',
 'ピー・シー・エー',
 '山洋電気',
 '一正蒲鉾',
 '白洋舎',
 'セントケア・ホールディング',
 '塩野義製薬',
 'オーバル',
 '清水建設',
 '中部飼料',
 'ＭｏｎｏｔａＲＯ',
 'ニプロ',
 'ゴルフダイジェスト・オンライン',
 '帝国電機製作所',
 'ＰＬＡＮＴ',
 '関東電化工業',
 '日本ＣＭＫ',
 '高砂香料工業',
 'サンマルクホールディングス',
 '九州電力',
 'はるやまホールディングス',
 'グランディハウス',
 '日本紙パルプ商事',
 '寿スピリッツ',
 '武蔵精密工業',
 '南陽',
 'ＳＵＢＡＲＵ',
 '浜松ホトニクス',
 'カナデン',
 '因幡電機産業',
 '戸田工業',
 'ダイビル',
 'イリソ電子工業',
 'ＳＢＳホールディングス',
 'いなげや',
 '森永乳業',
 'アーレスティ',
 'ＧＭＯペイメントゲートウェイ',
 '天馬',
 '富士急行',
 '伊藤忠テクノソリューションズ',
 '味の素',
 '村田製作所',
 'アイダエンジニアリング',
 '蝶理',
 'アキレス',
 'ヤマト',
 '星光ＰＭＣ',
 'コムチュア',
 '廣済堂',
 '東陽倉庫',
 '穴吹興産',
 'きちりホールディングス',
 'ザ・パック',
 '焼津水産化学工業',
 '三菱地所',
 'ニチレキ',
 'シンニッタン',
 'タムラ製作所',
 '東京応化工業',
 '住友商事',
 '渋沢倉庫',
 'ワイエイシイホールディングス',
 'ＡＮＡホールディングス',
 'サトーホールディングス',
 '富士興産',
 '東洋インキＳＣホールディングス',
 'ホギメディカル',
 'ＪＵＫＩ',
 '太平電業',
 'ダイニチ工業',
 '日本トリム',
 '名村造船所',
 '積水化学工業',
 'ＩＤホールディングス',
 '日立物流',
 '大阪チタニウムテクノロジーズ',
 'スカパーＪＳＡＴホールディング',
 'プリマハム',
 'ヤクルト本社',
 'トピー工業',
 'パイオラックス',
 '静岡ガス',
 'アルプスアルパイン',
 'コムシスホールディングス',
 'システムリサーチ',
 'サカタインクス',
 '中外炉工業',
 'コニカミノルタ',
 'ニチアス',
 'ベネッセホールディングス',
 'コンドーテック',
 'サックスバー\u3000ホールディングス',
 '京王電鉄',
 'クワザワホールディングス',
 '小糸製作所',
 'ソルクシーズ',
 '三菱商事',
 '東急',
 'ヨータイ',
 'エフ・シー・シー',
 'オーハシテクニカ',
 'ユニ・チャーム',
 'メイコー',
 '東京ガス',
 'ヒノキヤグループ',
 'エバラ食品工業',
 '日本カーボン',
 'ＴＰＲ',
 'アイロムグループ',
 '関西スーパーマーケット',
 '北陸電力',
 '小林製薬',
 'コメリ',
 'ユシロ化学工業',
 'ドウシシャ',
 'ＴＤＫ',
 'アイホン',
 'フジッコ',
 '稲畑産業',
 'ビーピー・カストロール',
 '日本高純度化学',
 '小松マテーレ',
 '東洋エンジニアリング',
 '大阪ソーダ',
 '市光工業',
 '協栄産業',
 'アルファシステムズ',
 'ジャパンベストレスキューシステ',
 '大塚商会',
 'エノモト',
 '東陽テクニカ',
 'リニカル',
 'トーヨーカネツ',
 '高千穂交易',
 '大気社',
 '日産自動車',
 'トーカイ',
 '石原産業',
 'やまや',
 'トランコム',
 '加藤産業',
 'アシックス',
 'アツギ',
 'ダイダン',
 '河西工業',
 'ミヨシ油脂',
 'ニチモウ',
 'ヤオコー',
 '日特建設',
 '井村屋グループ',
 '帝人',
 'アジアパイルホールディングス',
 'フジ・メディア・ホールディング',
 'バローホールディングス',
 'ケイヒン',
 '東京都競馬',
 '富士通',
 'エコナックホールディングス',
 '東都水産',
 '近鉄エクスプレス',
 'ＩＤＥＣ',
 'キヤノンマーケティングジャパン',
 '合同製鉄',
 '小森コーポレーション',
 'ワールドホールディングス',
 'ホクト',
 '松井建設',
 'イビデン',
 'ＥＭシステムズ',
 '三井Ｅ＆Ｓホールディングス',
 'ＳＣＳＫ',
 'マツモトキヨシホールディングス',
 '鳥居薬品',
 'メディカルシステムネットワーク',
 '三井住友建設',
 'ピエトロ',
 'スクロール',
 '三菱化工機',
 '日本精化',
 '日華化学',
 'アドウェイズ',
 '東洋シヤッター',
 '巴コーポレーション',
 '西華産業',
 '兼松サステック',
 '江崎グリコ',
 '宮地エンジニアリンググループ',
 'ブラザー工業',
 '日清食品ホールディングス',
 '昭和電線ホールディングス',
 'シード',
 '東洋機械金属',
 '第一屋製パン',
 'ＮＩＳＳＨＡ',
 'ダスキン',
 '北陸電気工業',
 '三井金属鉱業',
 '学研ホールディングス',
 '日本ヒューム',
 'ゼビオホールディングス',
 'トクヤマ',
 '日本ハム',
 'コア',
 'ジャストシステム',
 '西松建設',
 '東和薬品',
 '日本商業開発',
 '三菱鉛筆',
 '岡部',
 'アイネット',
 '亀田製菓',
 '日産東京販売ホールディングス',
 '藤倉コンポジット',
 '栗本鉄工所',
 'アドヴァングループ',
 'クレハ',
 '極東貿易',
 'メガチップス',
 '新日本科学',
 'リンクアンドモチベーション',
 'シーティーエス',
 'いすゞ自動車',
 '京三製作所',
 '京セラ',
 'ＯＢＡＲＡ\u3000ＧＲＯＵＰ',
 '東京エレクトロン',
 '沖縄電力',
 '東邦亜鉛',
 '鈴木',
 'セイコーホールディングス',
 '資生堂',
 'オイレス工業',
 'バンダイナムコホールディングス',
 'ＳＣＲＥＥＮホールディングス',
 'バルカー',
 'アドソル日進',
 'ダイドーリミテッド',
 '曙ブレーキ工業',
 '積水化成品工業',
 'アクセル',
 'ＤＯＷＡホールディングス',
 '日清紡ホールディングス',
 '日本セラミック',
 '有沢製作所',
 '大日本印刷',
 '神栄',
 'オルガノ',
 '新日本理化',
 'キーエンス',
 '日本ピラー工業',
 '横河ブリッジホールディングス',
 '日本航空電子工業',
 '魚力',
 '三浦工業',
 'ミロク情報サービス',
 'インテージホールディングス',
 'イエローハット',
 'エス・エム・エス',
 'ダイジェット工業',
 '三菱瓦斯化学',
 '植木組',
 '丸全昭和運輸',
 '尾家産業',
 '東海理化電機製作所',
 '西尾レントオール',
 'Ｈ．Ｕ．グループホールディング',
 '富士ソフト',
 'クリナップ',
 '日精樹脂工業',
 'エステールホールディングス',
 '日本電設工業',
 '川崎重工業',
 '電通国際情報サービス',
 '持田製薬',
 'サニーサイドアップグループ',
 '高松コンストラクショングループ',
 '不動テトラ',
 'ルネサスエレクトロニクス',
 '千趣会',
 '住友理工',
 'エー・アンド・デイ',
 '住友精密工業',
 'キャリアデザインセンター',
 '西日本鉄道',
 'ヤマタネ',
 'エーザイ',
 'ＧＭＯグローバルサイン・ホール',
 'セック',
 'マブチモーター',
 '野村総合研究所',
 '東レ',
 'メイテック',
 'ホソカワミクロン',
 'キリンホールディングス',
 'トーモク',
 '前沢給装工業',
 '東洋精糖',
 'ＴＯＡ',
 'テイクアンドギヴ・ニーズ',
 'デジタルガレージ',
 'ヴィア・ホールディングス',
 'プロトコーポレーション',
 'コナミホールディングス',
 'ナカノフドー建設',
 'メディパルホールディングス',
 '日本システムウエア',
 'デンカ',
 '日東富士製粉',
 '淀川製鋼所',
 'ファルコホールディングス',
 'ＷＯＷ\u3000ＷＯＲＬＤ',
 '平河ヒューテック',
 '永谷園ホールディングス',
 '阪和興業',
 'グリー',
 '三重交通グループホールディング',
 '安永',
 'アステリア',
 '日本山村硝子',
 'ジャムコ',
 'ランドビジネス',
 'レッグス',
 '東邦システムサイエンス',
 '伯東',
 '日本鋳鉄管',
 'ミマキエンジニアリング',
 '南海電気鉄道',
 '日本Ｍ＆Ａセンター',
 '三和ホールディングス',
 'ジェイエイシーリクルートメント',
 'モリタホールディングス',
 'エイベックス',
 '東京製鉄',
 'ヤマエ久野',
 'スズキ',
 'いであ',
 '大同メタル工業',
 'ハウス\u3000オブ\u3000ローゼ',
 'ＶＴホールディングス',
 'タムロン',
 '日新',
 '北沢産業',
 'タダノ',
 'トナミホールディングス',
 'スカラ',
 'エフピコ',
 'セントラルスポーツ',
 '長府製作所',
 '東邦アセチレン',
 '杉本商事',
 'ＳＨＯＥＩ',
 'ハマキョウレックス',
 'カネカ',
 '三菱ロジスネクスト',
 'イチネンホールディングス',
 '立川ブラインド工業',
 'ＪＣＲファーマ',
 '長谷工コーポレーション',
 '日本フエルト',
 'ＣＯＴＡ',
 'エックスネット',
 '東海カーボン',
 '三菱倉庫',
 'はせがわ',
 '日本新薬',
 '日本電子',
 'リョービ',
 'フィールズ',
 'ＵＴグループ',
 '日水製薬',
 '中央発条',
 '元気寿司',
 '小松ウオール工業',
 'サンデンホールディングス',
 '東京テアトル',
 '日置電機',
 'ヘリオス\u3000テクノ\u3000ホールディン',
 'ライオン',
 '住友重機械工業',
 'ヒロセ電機',
 'オーイズミ',
 'エン・ジャパン',
 'アルフレッサ\u3000ホールディングス',
 '渋谷工業',
 '荏原実業',
 '品川リフラクトリーズ',
 '北川鉄工所',
 'トーエネック',
 '近鉄グループホールディングス',
 '東京エレクトロン\u3000デバイス',
 '朝日工業社',
 'スクウェア・エニックス・ホール',
 'ビオフェルミン製薬',
 '富士通ゼネラル',
 '日本酸素ホールディングス',
 'ダントーホールディングス',
 '東急建設',
 'ゲオホールディングス',
 'バンドー化学',
 '日本エアーテック',
 'エスリード',
 'ＣＩＪ',
 '太陽誘電',
 'スタンレー電気',
 'ダイオーズ',
 '常磐興産',
 '日本製鋼所',
 'グルメ杵屋',
 '三桜工業',
 '東リ',
 '東武鉄道',
 'エムスリー',
 '平和不動産',
 '日清オイリオグループ',
 '丸文',
 'イノテック',
 'グンゼ',
 'タチエス',
 'トリドールホールディングス',
 'リケンテクノス',
 '第一工業製薬',
 '三井不動産',
 '立花エレテック',
 'ディア・ライフ',
 '北越コーポレーション',
 '日阪製作所',
 '黒崎播磨',
 'レシップホールディングス',
 'サイバネットシステム',
 'セイコーエプソン',
 '石川製作所',
 '新電元工業',
 'ドリームインキュベータ',
 'クボタ',
 '任天堂',
 '日本金銭機械',
 '東京製綱',
 '熊谷組',
 '遠藤照明',
 '蛇の目ミシン工業',
 'ＪＣＵ',
 'コニシ',
 'リコー',
 'キトー',
 '日本空調サービス',
 'アサヒグループホールディングス',
 'ニッタ',
 'オプテックスグループ',
 'キムラタン',
 '東亜道路工業',
 'サイバーエージェント',
 'デサント',
 'アウトソーシング',
 'フォスター電機',
 '山善',
 '養命酒製造',
 '都築電気',
 '新日本電工',
 'ジーテクト',
 'カワタ',
 'ウッドワン',
 'ペッパーフードサービス',
 'サニックス',
 '福山通運',
 '富士製薬工業',
 '日東工器',
 'ヤマダホールディングス',
 'ゼンショーホールディングス',
 '東京計器',
 '帝国繊維',
 '片倉コープアグリ',
 '三谷産業',
 '第一カッター興業',
 '福井コンピュータホールディング',
 'ＮＩＰＰＯ',
 '五洋建設',
 '飛島建設',
 'シミックホールディングス',
 'ルネサンス',
 '大崎電気工業',
 'オカモト',
 '浅沼組',
 '大豊工業',
 'ＵＡＣＪ',
 'たけびし',
 'メルコホールディングス',
 '東亜ディーケーケー',
 '双信電機',
 'ティーガイア',
 'スターゼン',
 '王将フードサービス',
 'マツダ',
 '住友電設',
 'ＧＭＢ',
 'オリエンタルランド',
 'レオン自動機',
 '京阪神ビルディング',
 'アートネイチャー',
 'アゴーラ\u3000ホスピタリティー\u3000グ',
 '日鉄鉱業',
 'イチカワ',
 '日本システム技術',
 '白銅',
 'マースグループホールディングス',
 'アイ・オー・データ機器',
 '武田薬品工業',
 '未来工業',
 'ぴあ',
 'インフォマート',
 '東邦瓦斯',
 'エイチ・ツー・オー\u3000リテイリン',
 '山一電機',
 '生化学工業',
 '伊藤忠商事',
 'グローセル',
 '三井物産',
 '日東精工',
 '岩崎電気',
 'アイティメディア',
 '綜合警備保障',
 'セーレン',
 'フジ住宅',
 '山陽特殊製鋼',
 'ローランド\u3000ディー．ジー．',
 '進学会ホールディングス',
 '日本甜菜製糖',
 '藤倉化成',
 '日本基礎技術',
 'ミネベアミツミ',
 'ＣＡＣ\u3000Ｈｏｌｄｉｎｇｓ',
 '三機工業',
 '三井化学',
 'アルファ',
 '盟和産業',
 'ニコン',
 '三菱自動車工業',
 '近畿車両',
 'ＴＯＹＯ\u3000ＴＩＲＥ',
 '大紀アルミニウム工業所',
 'キムラユニティー',
 '出光興産',
 '神奈川中央交通',
 'ナカバヤシ',
 '日野自動車',
 '信越化学工業',
 'アステラス製薬',
 '横河電機',
 'ファンコミュニケーションズ',
 'タナベ経営',
 '椿本チエイン',
 'アイシン',
 'キヤノン電子',
 'バリューコマース',
 '九電工',
 'ＪＫホールディングス',
 'エフ・ジェー・ネクスト',
 '積水樹脂',
 '三晃金属工業',
 '住友ゴム工業',
 'インフォコム',
 'イトーキ',
 '加藤製作所',
 '日本ペイントホールディングス',
 'ＥＰＳホールディングス',
 'ブロンコビリー',
 '新日本建設',
 'イソライト工業',
 'エヌ・ティ・ティ・データ',
 '島精機製作所',
 '芦森工業',
 'レンゴー',
 'ＬＩＦＵＬＬ',
 '丸大食品',
 'ＳＡＮＫＹＯ',
 'パイロットコーポレーション',
 'ＧＭＯインターネット',
 '丸山製作所',
 '東京鉄鋼',
 'グリムス',
 '明和地所',
 '東洋埠頭',
 'ＯＫＩ',
 '船井電機',
 'ＢＥＥＮＯＳ',
 '建設技術研究所',
 '日本板硝子',
 'ジーエス・ユアサ\u3000コーポレーシ',
 '東亜建設工業',
 '日本特殊塗料',
 '安藤・間',
 'アマノ',
 'ＴＯＴＯ',
 '日本郵船',
 'ノーリツ鋼機',
 'タケエイ',
 'ビジネス・ブレークスルー',
 'ひらまつ',
 '日本工営',
 'ニッカトー',
 'サンリツ',
 '中電工',
 'リンテック',
 '日伝',
 'ユニカフェ',
 '宝ホールディングス',
 '日立造船',
 '電源開発',
 '名古屋鉄道',
 'ツツミ',
 'ココカラファイン',
 '丸運',
 '群栄化学工業',
 'ソフトバンクグループ',
 '大豊建設',
 '住友精化',
 '神鋼商事',
 '東京精密',
 '北野建設',
 'フルサト工業',
 '川崎汽船',
 '日精エー・エス・ビー機械',
 '相鉄ホールディングス',
 'エフオン',
 '北海道電力',
 'デリカフーズホールディングス',
 '鹿島',
 'フジシールインターナショナル',
 '東プレ',
 '日本ギア工業',
 'サンケン電気',
 '昭和電工',
 '沢藤電機',
 'ＫＩＭＯＴＯ',
 'リログループ',
 'ＪＢＣＣホールディングス',
 '東海旅客鉄道',
 '幸楽苑ホールディングス',
 'ハイマックス',
 '本田技研工業',
 '宇部興産',
 '東日本旅客鉄道',
 'コロナ',
 'ＳＲＡホールディングス',
 'ヤマハ',
 '大林組',
 '高島',
 'アルバック',
 '富士電機',
 '関西電力',
 '双葉電子工業',
 'ＫＮＴ－ＣＴホールディングス',
 'トーア紡コーポレーション',
 'イフジ産業',
 '明星工業',
 '三井松島ホールディングス',
 '油研工業',
 'あみやき亭',
 '東祥',
 'エンシュウ',
 'タクマ',
 'ユニプレス',
 '東京エネシス',
 'インテリジェント\u3000ウェイブ',
 '日本道路',
 'ケーズホールディングス',
 'ＳＭＣ',
 '帝国通信工業',
 '日本精工',
 'タカキタ',
 'トーカロ',
 '三ツ星ベルト',
 'タカラトミー',
 '大真空',
 '文化シヤッター',
 'ＥＩＺＯ',
 '矢作建設工業',
 'アルプス物流',
 'ソニーグループ',
 'トプコン',
 'Ｔ＆Ｋ\u3000ＴＯＫＡ',
 'サッポロホールディングス',
 'メック',
 '扶桑化学工業',
 'シマノ',
 'タキロンシーアイ',
 'オリンパス',
 'ゴールドクレスト',
 'ツガミ',
 'ブリヂストン',
 'ディスコ',
 '中央倉庫',
 'ナブテスコ',
 '多木化学',
 'フジミインコーポレーテッド',
 'サンワテクノス',
 'ダイトウボウ',
 '三井海洋開発',
 '東洋紡',
 '石油資源開発',
 '日本通信',
 'ＫＹＢ',
 '理想科学工業',
 '岩崎通信機',
 'ＮＥＣ',
 '東ソー',
 'ワタミ',
 '三菱電機',
 'カゴメ',
 'コカ・コーラ\u3000ボトラーズジャパ',
 '橋本総業ホールディングス',
 'オークマ',
 '宇徳',
 '東鉄工業',
 '旭ダイヤモンド工業',
 'シンフォニア\u3000テクノロジー',
 'サンゲツ',
 'ＭＵＴＯＨホールディングス',
 '夢真ビーネックスグループ',
 'ＣＤＧ',
 '石原ケミカル',
 'アドバンテスト',
 'ミスミグループ本社',
 'トヨタ自動車',
 '日本光電',
 'サンドラッグ',
 '三菱重工業',
 '日本農薬',
 '明治海運',
 '兼松',
 'ステラ\u3000ケミファ',
 '松田産業',
 'グローリー',
 'エスペック',
 'トヨタ紡織',
 'オエノンホールディングス',
 '東芝テック',
 'ペガサスミシン製造',
 '朝日放送グループホールディング',
 'きんでん',
 'オービックビジネスコンサルタン',
 '東北電力',
 'ティラド',
 'ジェコス',
 '鉄建建設',
 'グローブライド',
 '木村化工機',
 'デジタルアーツ',
 'リズム',
 'ルックホールディングス',
 '平田機工',
 'タカラレーベン',
 'ヤマハ発動機',
 'ＴＢＫ',
 'ヨロズ',
 'アネスト岩田',
 'スミダコーポレーション',
 'エレコム',
 '日本管財',
 'ニップン',
 '小野測器',
 'ハウス食品グループ本社',
 'オートバックスセブン',
 '前田道路',
 '日本製鉄',
 'シスメックス',
 'マルシェ',
 'カメイ',
 'ＳＲＳホールディングス',
 '日工',
 'アイ・エス・ビー',
 '富士石油',
 'ニチレイ',
 '北海道ガス',
 '朝日インテック',
 'アイフィスジャパン',
 'ピーエス三菱',
 'モーニングスター',
 '日本ケミファ',
 'ＳＭＫ',
 'ライト工業',
 'レック',
 '不二家',
 '光通信',
 'ラウンドワン',
 'ノジマ',
 '不二製油グループ本社',
 'ユー・エス・エス',
 'ワコム',
 '星和電機',
 '伊藤忠エネクス',
 'ニチハ',
 'ＭＡＲＵＷＡ',
 'キューブシステム',
 'ビジネスエンジニアリング',
 'ファナック',
 'シャープ',
 '兼松エレクトロニクス',
 'プレステージ・インターナショナ',
 '電通グループ',
 '三菱製紙',
 'ティア',
 '日本冶金工業',
 '西部ガスホールディングス',
 '大成建設',
 '扶桑薬品工業',
 'ＣＥホールディングス',
 'サンコール',
 '三愛石油',
 '東海運',
 'フォーカスシステムズ',
 '三菱マテリアル',
 'ビーアールホールディングス',
 'ネツレン',
 '共同印刷',
 'ＣＫサンエツ',
 '理研ビタミン',
 '大日精化工業',
 '長谷川香料',
 'オカムラ',
 'ＮＴＮ',
 '銭高組',
 'プレス工業',
 '日本通運',
 '住友金属鉱山',
 '第一興商',
 '三井倉庫ホールディングス',
 'エア・ウォーター',
 'ニホンフラッシュ',
 'ゼンリン',
 'ＴＹＫ',
 'アリアケジャパン',
 '加賀電子',
 'トラスコ中山',
 '三共生興',
 'ＮＯＫ',
 'ソディック',
 '飯野海運',
 '日油',
 'ＰＡＬＴＡＣ',
 '日本電信電話',
 'リゾートトラスト',
 '日比谷総合設備',
 'ケンコーマヨネーズ',
 '四国化成工業',
 'ＩＭＡＧＩＣＡ\u3000ＧＲＯＵＰ',
 'パン・パシフィック・インターナ',
 'セコム',
 'マックス',
 '平和',
 'オカダアイヨン',
 '大平洋金属',
 '昭文社ホールディングス',
 'ショーボンドホールディングス',
 '住友倉庫',
 '住友化学',
 'ウシオ電機',
 'インプレスホールディングス',
 'ハークスレイ',
 '東洋製缶グループホールディング',
 'ホーチキ',
 '大阪製鉄',
 'アズワン',
 '小田急電鉄',
 'オービック',
 '光村印刷',
 'ガンホー・オンライン・エンター',
 'ベルーナ',
 'エムティーアイ',
 '大倉工業',
 'ニッパツ',
 'ハイパー',
 '大王製紙',
 'ケーユーホールディングス',
 'クオールホールディングス',
 '小野建',
 '極洋',
 '日本ゼオン',
 'ダイコク電機',
 '石塚硝子',
 '虹技',
 'フェイス',
 '荒川化学工業',
 '日本電波工業',
 '中部電力',
 'アルビス',
 '菱電商事',
 '船井総研ホールディングス',
 '山陽電気鉄道',
 'ホクシン',
 'サイネックス',
 '東洋水産',
 'ソトー',
 'テレビ朝日ホールディングス',
 'フジテック',
 '前田工繊',
 'コーセー',
 '日神グループホールディングス',
 'ハピネット',
 'カシオ計算機',
 '日進工具',
 '関西ペイント',
 '藤森工業',
 '蔵王産業',
 'ミクシィ',
 '新東工業',
 '日産化学',
 '松屋フーズホールディングス',
 'アルコニックス',
 '松風',
 'エス・サイエンス',
 'ソネック',
 'ブイ・テクノロジー',
 '日本精線',
 'ダイセル',
 'ＷＤＢホールディングス',
 'ファンケル',
 'ユアテック',
 '高田機工',
 '電気興業',
 '住友大阪セメント',
 'テイカ',
 '芝浦機械',
 '藤久',
 '住友電気工業',
 '日本プラスト',
 'クリエートメディック',
 'タカノ',
 '日本化学工業',
 'アクシアル\u3000リテイリング',
 'ホシデン',
 '島津製作所',
 'ソリトンシステムズ',
 'ＮＳＤ',
 '塩水港精糖',
 '共和電業',
 'アルインコ',
 'プロネクサス',
 'アイコム',
 'フコク',
 'ユーシン精機',
 '東京電力ホールディングス',
 '富士フイルムホールディングス',
 'ＷＯＷＯＷ',
 '日本曹達',
 'フタバ産業',
 ...}